import logging
from typing import List, Optional
from app.core.supabase import get_supabase_client
from app.models.schemas import Exercise

logger = logging.getLogger(__name__)

# ==============================================================================
# CATALOGUE COMPLET DES 49 EXERCICES DE BASE (Coaching_IA_Base_V1)
# ==============================================================================
DEFAULT_EXERCISES: List[Exercise] = [
    Exercise(
        code_id="STR-001",
        name="Air Squat",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Débutant",
        objective="Force / Endurance",
        material="Aucun",
        main_zone="Quadriceps",
        secondary_zones="Fessiers, Core",
        joint_impact="Faible",
        repetitions="15",
        series="3",
        rest="60 s",
        instructions="Descendre jusqu'à cuisses parallèles, talons au sol",
        common_mistakes="Genoux qui rentrent, dos rond",
        progression="Goblet Squat",
        regression="Box Squat",
        contraindications="Douleur ou instabilité",
        tags="Force, Débutant, Maison, Full Body",
        video_url="https://youtube.com/shorts/8voSXZyTp2A"
    ),
    Exercise(
        code_id="STR-002",
        name="Goblet Squat",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Force",
        material="Haltère/Kettlebell",
        main_zone="Quadriceps",
        secondary_zones="Fessiers, Core",
        joint_impact="Moyen",
        repetitions="12",
        series="4",
        rest="90 s",
        instructions="Garder le poids proche de la poitrine",
        common_mistakes="Pencher le buste",
        progression="Front Squat",
        regression="Air Squat",
        contraindications="Lombalgie aiguë",
        tags="Force, Haltère",
        video_url="https://youtube.com/shorts/Bt8lsQStck0"
    ),
    Exercise(
        code_id="STR-003",
        name="Bulgarian Split Squat",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Force unilatérale",
        material="Banc + Haltères",
        main_zone="Quadriceps",
        secondary_zones="Fessiers",
        joint_impact="Moyen",
        repetitions="10/jambe",
        series="3",
        rest="90 s",
        instructions="Genou aligné avec le pied",
        common_mistakes="Perte d'équilibre",
        progression="Avec charge",
        regression="Fente arrière",
        contraindications="Douleur importante au genou",
        tags="Unilatéral",
        video_url="https://youtube.com/shorts/uBSoEWZu07k"
    ),
    Exercise(
        code_id="STR-004",
        name="Walking Lunge",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Débutant",
        objective="Endurance musculaire",
        material="Aucun",
        main_zone="Quadriceps",
        secondary_zones="Fessiers",
        joint_impact="Moyen",
        repetitions="20 pas",
        series="3",
        rest="60 s",
        instructions="Faire de grandes foulées",
        common_mistakes="Genou avant dépasse excessivement",
        progression="Avec haltères",
        regression="Fente statique",
        contraindications="Douleur genou",
        tags="Fentes",
        video_url="https://youtube.com/shorts/Agmpy7Pj1Nw"
    ),
    Exercise(
        code_id="STR-005",
        name="Glute Bridge",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Débutant",
        objective="Activation fessiers",
        material="Aucun",
        main_zone="Fessiers",
        secondary_zones="Ischio-jambiers",
        joint_impact="Faible",
        repetitions="20",
        series="3",
        rest="45 s",
        instructions="Monter les hanches complètement",
        common_mistakes="Hyperextension lombaire",
        progression="Hip Thrust",
        regression="Bridge partiel",
        contraindications="Aucune",
        tags="Fessiers, Prévention",
        video_url="https://youtube.com/shorts/RrU4zx4ysnI"
    ),
    Exercise(
        code_id="STR-006",
        name="Hip Thrust",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Puissance hanches",
        material="Barre",
        main_zone="Fessiers",
        secondary_zones="Ischios",
        joint_impact="Moyen",
        repetitions="10",
        series="4",
        rest="90 s",
        instructions="Contracter les fessiers en haut",
        common_mistakes="Extension lombaire",
        progression="Plus lourd",
        regression="Glute Bridge",
        contraindications="Douleur lombaire",
        tags="Puissance",
        video_url="https://youtube.com/shorts/CvuVYMFd11g"
    ),
    Exercise(
        code_id="STR-007",
        name="Romanian Deadlift",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Chaîne postérieure",
        material="Barre/Haltères",
        main_zone="Ischio-jambiers",
        secondary_zones="Lombaires, Fessiers",
        joint_impact="Moyen",
        repetitions="10",
        series="4",
        rest="90 s",
        instructions="Garder le dos neutre",
        common_mistakes="Arrondir le dos",
        progression="Deadlift",
        regression="Good Morning sans charge",
        contraindications="Lombalgie aiguë",
        tags="Ischios",
        video_url="https://youtube.com/shorts/_TchJLlBO-4"
    ),
    Exercise(
        code_id="STR-008",
        name="Step Up",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Débutant",
        objective="Force fonctionnelle",
        material="Banc",
        main_zone="Quadriceps",
        secondary_zones="Fessiers",
        joint_impact="Faible",
        repetitions="12/jambe",
        series="3",
        rest="60 s",
        instructions="Pousser avec la jambe sur le banc",
        common_mistakes="Prendre de l'élan avec la jambe arrière",
        progression="Avec haltères",
        regression="Banc plus bas",
        contraindications="Douleur genou",
        tags="Fonctionnel",
        video_url="https://youtube.com/shorts/TG3xUe-UvCQ"
    ),
    Exercise(
        code_id="STR-009",
        name="Wall Sit",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="Débutant",
        objective="Endurance",
        material="Mur",
        main_zone="Quadriceps",
        secondary_zones="Core",
        joint_impact="Faible",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Garder les cuisses parallèles",
        common_mistakes="Monter ou descendre trop",
        progression="Plus long",
        regression="Angle moins fermé",
        contraindications="Douleur rotulienne",
        tags="Isométrique",
        video_url="https://youtube.com/shorts/mDdLC-yKudY"
    ),
    Exercise(
        code_id="STR-010",
        name="Box Jump",
        family="Force",
        subfamily="Bas du corps",
        discipline="Cross Training",
        level="Avancé",
        objective="Explosivité",
        material="Box",
        main_zone="Quadriceps",
        secondary_zones="Mollets",
        joint_impact="Élevé",
        repetitions="8",
        series="4",
        rest="90 s",
        instructions="Atterrir en douceur",
        common_mistakes="Genoux en valgus",
        progression="Box plus haute",
        regression="Squat Jump",
        contraindications="Problèmes de genoux/chevilles, NO_JUMP",
        tags="Explosivité",
        video_url="https://youtube.com/shorts/vBZ9N6KnLI8"
    ),
    Exercise(
        code_id="UPP-001",
        name="Pompes classiques",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Musculation",
        level="Débutant",
        objective="Force / Endurance",
        material="Aucun",
        main_zone="Pectoraux",
        secondary_zones="Triceps, Épaules, Core",
        joint_impact="Faible",
        repetitions="12",
        series="3",
        rest="60 s",
        instructions="Corps gainé, poitrine proche du sol",
        common_mistakes="Hanches qui tombent, coudes trop ouverts",
        progression="Pompes déclinées",
        regression="Pompes sur genoux",
        contraindications="Douleur aiguë à l'épaule",
        tags="Push, Maison, Débutant",
        video_url="https://youtube.com/shorts/n8PJC6yo_1o"
    ),
    Exercise(
        code_id="UPP-002",
        name="Développé couché",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Force maximale",
        material="Barre",
        main_zone="Pectoraux",
        secondary_zones="Triceps, Deltoïdes",
        joint_impact="Moyen",
        repetitions="8",
        series="4",
        rest="120 s",
        instructions="Omoplates serrées, pieds ancrés",
        common_mistakes="Rebondir sur la poitrine",
        progression="Plus lourd",
        regression="Développé haltères",
        contraindications="Blessure épaule",
        tags="Salle, Force",
        video_url="https://youtube.com/shorts/Jc06xowWeI4"
    ),
    Exercise(
        code_id="UPP-003",
        name="Développé haltères",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Musculation",
        level="Débutant",
        objective="Hypertrophie",
        material="Haltères",
        main_zone="Pectoraux",
        secondary_zones="Triceps",
        joint_impact="Faible",
        repetitions="12",
        series="3",
        rest="90 s",
        instructions="Mouvement contrôlé",
        common_mistakes="Amplitude incomplète",
        progression="Banc incliné",
        regression="Pompes",
        contraindications="Épaule instable",
        tags="Haltères",
        video_url="https://youtube.com/shorts/xoTdvzKWib8"
    ),
    Exercise(
        code_id="UPP-004",
        name="Développé militaire",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Force épaules",
        material="Barre",
        main_zone="Deltoïdes",
        secondary_zones="Triceps, Core",
        joint_impact="Moyen",
        repetitions="8",
        series="4",
        rest="90 s",
        instructions="Contracter les abdos",
        common_mistakes="Hyperlordose",
        progression="Push Press",
        regression="Développé haltères assis",
        contraindications="Douleur cervicale",
        tags="Épaules",
        video_url="https://youtube.com/shorts/TH8ovIkkkLk"
    ),
    Exercise(
        code_id="UPP-005",
        name="Développé Arnold",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Hypertrophie épaules",
        material="Haltères",
        main_zone="Deltoïdes",
        secondary_zones="Triceps",
        joint_impact="Faible",
        repetitions="10",
        series="3",
        rest="75 s",
        instructions="Rotation fluide",
        common_mistakes="Rotation trop rapide",
        progression="Plus lourd",
        regression="Développé haltères",
        contraindications="Douleur épaule",
        tags="Arnold Press",
        video_url="https://youtube.com/shorts/KYYNNj4v2J0"
    ),
    Exercise(
        code_id="UPP-006",
        name="Dips",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Musculation",
        level="Avancé",
        objective="Force",
        material="Barres parallèles",
        main_zone="Triceps",
        secondary_zones="Pectoraux",
        joint_impact="Élevé",
        repetitions="10",
        series="4",
        rest="90 s",
        instructions="Descendre sous les 90° sans douleur",
        common_mistakes="Épaules qui remontent",
        progression="Dips lestés",
        regression="Bench Dips",
        contraindications="Épaule instable",
        tags="Triceps",
        video_url="https://youtube.com/shorts/CrbIq-T-h8I"
    ),
    Exercise(
        code_id="UPP-007",
        name="Push Press",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Haltérophilie",
        level="Avancé",
        objective="Puissance",
        material="Barre",
        main_zone="Deltoïdes",
        secondary_zones="Triceps, Jambes",
        joint_impact="Moyen",
        repetitions="6",
        series="5",
        rest="120 s",
        instructions="Utiliser l'impulsion des jambes",
        common_mistakes="Pousser uniquement avec les bras",
        progression="Plus lourd",
        regression="Développé militaire",
        contraindications="Lombalgie aiguë",
        tags="Puissance",
        video_url="https://youtube.com/shorts/VaIDqmZBkpc"
    ),
    Exercise(
        code_id="UPP-008",
        name="Landmine Press",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Force fonctionnelle",
        material="Barre Landmine",
        main_zone="Deltoïdes",
        secondary_zones="Pectoraux, Core",
        joint_impact="Faible",
        repetitions="10/bras",
        series="3",
        rest="75 s",
        instructions="Pousser dans l'axe",
        common_mistakes="Rotation du tronc",
        progression="Debout unilatéral",
        regression="Développé haltères",
        contraindications="Aucune spécifique",
        tags="Fonctionnel",
        video_url="https://youtube.com/shorts/Iu5pYQEkj38"
    ),
    Exercise(
        code_id="UPP-009",
        name="Pompes explosives",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Préparation physique",
        level="Avancé",
        objective="Explosivité",
        material="Aucun",
        main_zone="Pectoraux",
        secondary_zones="Triceps",
        joint_impact="Moyen",
        repetitions="8",
        series="5",
        rest="90 s",
        instructions="Décoller les mains rapidement",
        common_mistakes="Mauvaise réception",
        progression="Pompes claquées",
        regression="Pompes classiques",
        contraindications="Poignets douloureux",
        tags="Explosivité",
        video_url="https://youtube.com/shorts/2JxSJyt_IMk"
    ),
    Exercise(
        code_id="UPP-010",
        name="Pike Push-Up",
        family="Force",
        subfamily="Haut du corps poussée",
        discipline="Calisthenics",
        level="Intermédiaire",
        objective="Force verticale",
        material="Aucun",
        main_zone="Deltoïdes",
        secondary_zones="Triceps",
        joint_impact="Moyen",
        repetitions="10",
        series="3",
        rest="60 s",
        instructions="Descendre la tête entre les mains",
        common_mistakes="Dos arrondi",
        progression="Handstand Push-Up",
        regression="Pompes inclinées",
        contraindications="Douleur cervicale",
        tags="Poids du corps",
        video_url="https://youtube.com/shorts/UalsVVpBacw"
    ),
    Exercise(
        code_id="THC-001",
        name="Tractions pronination (Pull-ups)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Calisthenics",
        level="Avancé",
        objective="Force dos / Largeur",
        material="Barre de traction",
        main_zone="Grand dorsal",
        secondary_zones="Biceps, Grand rond, Trapèzes",
        joint_impact="Moyen",
        repetitions="6",
        series="3",
        rest="90 s",
        instructions="Prise un peu plus large que les épaules, tirer les coudes vers le bas",
        common_mistakes="Balancement du corps, amplitude incomplète",
        progression="Tractions lestées",
        regression="Tractions assistées avec élastique",
        contraindications="Douleur aiguë à l'épaule ou au coude",
        tags="Dos, Largeur, Avancé",
        video_url="https://youtube.com/shorts/ym1V5H35IpA"
    ),
    Exercise(
        code_id="THC-002",
        name="Tractions supination (Chin-ups)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Calisthenics",
        level="Intermédiaire",
        objective="Force dos et biceps",
        material="Barre de traction",
        main_zone="Grand dorsal",
        secondary_zones="Biceps brachial",
        joint_impact="Moyen",
        repetitions="8",
        series="3",
        rest="90 s",
        instructions="Paumes de mains vers soi, prise largeur d'épaules",
        common_mistakes="Ne pas tendre complètement les bras en bas",
        progression="Tractions supination lestées",
        regression="Tractions australiennes",
        contraindications="Tendinite au coude",
        tags="Biceps, Dos, Intermédiaire",
        video_url="https://youtube.com/shorts/Oi3bW9nQmGI"
    ),
    Exercise(
        code_id="THC-003",
        name="Tirage horizontal unilatéral aux haltères (Rowing)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Musculation",
        level="Débutant",
        objective="Épaisseur du dos",
        material="Banc et Haltère",
        main_zone="Grand dorsal",
        secondary_zones="Romboïdes, Biceps, Trapèzes",
        joint_impact="Faible",
        repetitions="10/bras",
        series="3",
        rest="75 s",
        instructions="Un genou et une main sur le banc, tirer l'haltère vers la hanche",
        common_mistakes="Rotation excessive du tronc, tirer avec le bras",
        progression="Rowing barre lourd",
        regression="Rowing buste penché léger",
        contraindications="Lombalgie sensible",
        tags="Dos, Unilatéral, Maison",
        video_url="https://youtube.com/shorts/vu_YDt9nGv4"
    ),
    Exercise(
        code_id="THC-004",
        name="Rowing buste penché aux haltères",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Épaisseur globale du dos",
        material="Haltères",
        main_zone="Grand dorsal",
        secondary_zones="Romboïdes, Érecteurs du rachis",
        joint_impact="Moyen",
        repetitions="10",
        series="3",
        rest="90 s",
        instructions="Buste penché à 45°, dos plat",
        common_mistakes="Arrondir le dos pendant le tirage",
        progression="Rowing barre olympique",
        regression="Rowing sur banc incliné",
        contraindications="Hernie discale",
        tags="Dos, Épaisseur",
        video_url="https://youtube.com/shorts/dpYI8K6e-jE"
    ),
    Exercise(
        code_id="THC-005",
        name="Tractions australiennes (Inverted Row)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Calisthenics",
        level="Débutant",
        objective="Renforcement dos accessible",
        material="Barre fixe basse ou TRX",
        main_zone="Grand dorsal",
        secondary_zones="Romboïdes, Biceps",
        joint_impact="Faible",
        repetitions="12",
        series="3",
        rest="60 s",
        instructions="Corps aligné sous la barre, tirer la poitrine contre la barre",
        common_mistakes="Laisser creuser les hanches",
        progression="Tractions classiques",
        regression="Tractions australiennes jambes fléchies",
        contraindications="Aucune spécifique",
        tags="Débutant, Maison, TRX",
        video_url="https://youtube.com/shorts/qfsEK96Px-E"
    ),
    Exercise(
        code_id="COR-001",
        name="Gainage planche forearm (Plank)",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="Débutant",
        objective="Stabilité lombo-abdominale",
        material="Aucun",
        main_zone="Grand droit de l'abdomen",
        secondary_zones="Transverse, Épaules, Fessiers",
        joint_impact="Faible",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Appui sur les avant-bras et pointes de pieds, bassin en rétroversion",
        common_mistakes="Fesses trop hautes ou bassin qui s'affaisse",
        progression="Planche dynamique / sur une main",
        regression="Planche sur les genoux",
        contraindications="Lombalgie aiguë en extension",
        tags="Core, Maison, Débutant",
        video_url="https://youtube.com/shorts/E-PBfoIMc-0"
    ),
    Exercise(
        code_id="COR-002",
        name="Gainage latéral (Side Plank)",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="Intermédiaire",
        objective="Stabilité latérale / Obliques",
        material="Aucun",
        main_zone="Obliques",
        secondary_zones="Carré des lombaires, Moyen fessier",
        joint_impact="Faible",
        duration="30 s/côté",
        series="3",
        rest="45 s",
        instructions="Appui sur l'avant-bras latéral, alignement parfait",
        common_mistakes="Hanches qui piquent vers le sol",
        progression="Gainage latéral avec élévation de jambe",
        regression="Gainage latéral sur les genoux",
        contraindications="Douleur à l'épaule d'appui",
        tags="Core, Obliques, Unilatéral",
        video_url="https://youtube.com/shorts/eZQRj1yG-gY"
    ),
    Exercise(
        code_id="COR-003",
        name="Bird Dog (Quadrupède)",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="Débutant",
        objective="Stabilité rachidienne / Posture",
        material="Aucun",
        main_zone="Érecteurs du rachis",
        secondary_zones="Fessiers, Core",
        joint_impact="Faible",
        repetitions="10/côté",
        series="3",
        rest="60 s",
        instructions="À quatre pattes, tendre bras droit et jambe gauche sans bouger le bassin",
        common_mistakes="Rotation du bassin lors de l'extension",
        progression="Bird Dog avec résistance élastique",
        regression="Extension unilatérale bras seul",
        contraindications="Aucune spécifique",
        tags="Core, Santé du dos, Débutant",
        video_url="https://youtube.com/shorts/vtwhC3tfVow"
    ),
    Exercise(
        code_id="COR-004",
        name="Dead Bug",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="Débutant",
        objective="Contrôle lombo-pelvien",
        material="Aucun",
        main_zone="Transverse de l'abdomen",
        secondary_zones="Fléchisseurs de la hanche",
        joint_impact="Faible",
        repetitions="10/côté",
        series="3",
        rest="60 s",
        instructions="Allongé sur le dos, bras levés, genoux à 90°",
        common_mistakes="Lombales qui se décollent du sol",
        progression="Dead Bug avec charge aux mains",
        regression="Dead Bug jambes fléchies",
        contraindications="Douleur lombaire",
        tags="Core, Posture, Abdominaux",
        video_url="https://youtube.com/shorts/5c-vucY3beU"
    ),
    Exercise(
        code_id="COR-005",
        name="Mountain Climbers",
        family="Gainage",
        subfamily="Core / Cardio",
        discipline="Préparation physique",
        level="Intermédiaire",
        objective="Cardio & Gainage dynamique",
        material="Aucun",
        main_zone="Core",
        secondary_zones="Épaules, Quadriceps",
        joint_impact="Moyen",
        duration="45 s",
        series="3",
        rest="60 s",
        instructions="Position de pompe, ramener alternativement les genoux vers la poitrine",
        common_mistakes="Fesses qui montent trop haut",
        progression="Mountain climbers rapides ou croisés",
        regression="Mountain climbers lents en marchant",
        contraindications="Douleur aux poignets",
        tags="Core, Cardio, Dynamique",
        video_url="https://youtube.com/shorts/7W4JEfEKuC4"
    ),
    Exercise(
        code_id="CAR-001",
        name="Jumping Jacks",
        family="Cardio",
        subfamily="Cardio basique",
        discipline="Préparation physique",
        level="Débutant",
        objective="Endurance cardiovasculaire",
        material="Aucun",
        main_zone="Système cardiovasculaire",
        secondary_zones="Mollets, Épaules",
        joint_impact="Faible",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Sauter en écartant les jambes et en levant les bras",
        common_mistakes="Amorti trop lourd sur les articulations",
        progression="Jumping Jacks rythmés lestés",
        regression="Jumping Jacks sans saut",
        contraindications="Douleur aux genoux ou chevilles, NO_JUMP",
        tags="Cardio, Échauffement, Maison",
        video_url="https://youtube.com/shorts/yg3KQQn3QWg"
    ),
    Exercise(
        code_id="CAR-002",
        name="Corde à sauter",
        family="Cardio",
        subfamily="Cardio dynamique",
        discipline="Préparation physique",
        level="Intermédiaire",
        objective="Agilité / Cardio",
        material="Corde à sauter",
        main_zone="Système cardiovasculaire",
        secondary_zones="Mollets, Avant-bras",
        joint_impact="Moyen",
        duration="60 s",
        series="3",
        rest="60 s",
        instructions="Sauts courts impulsés par les poignets",
        common_mistakes="Sauter trop haut ou utiliser les bras",
        progression="Double unders",
        regression="Sauts sur place sans corde",
        contraindications="Fasciite plantaire / Douleur tibiale, NO_JUMP",
        tags="Cardio, Agilité",
        video_url="https://youtube.com/shorts/iWa7KVOyAlU"
    ),
    Exercise(
        code_id="CAR-003",
        name="Burpees sans pompe",
        family="Cardio",
        subfamily="Cardio / Full Body",
        discipline="Préparation physique",
        level="Intermédiaire",
        objective="Puissance aérobie",
        material="Aucun",
        main_zone="Corps entier",
        secondary_zones="Quadriceps, Pectoraux, Core",
        joint_impact="Élevé",
        repetitions="10",
        series="3",
        rest="75 s",
        instructions="Passer accroupi, envoyer les pieds en arrière, ramener et sauter",
        common_mistakes="Laisser creuser le dos en planche",
        progression="Burpees complets avec pompe et saut",
        regression="Burpees en marchant",
        contraindications="Lombalgie ou douleur poignets, NO_JUMP",
        tags="Cardio, Intensité",
        video_url="https://youtube.com/shorts/GJ2oJUrsm7s"
    ),
    Exercise(
        code_id="CAR-004",
        name="High Knees (Genoux montants)",
        family="Cardio",
        subfamily="Cardio dynamique",
        discipline="Préparation physique",
        level="Débutant",
        objective="Explosivité / Cardio",
        material="Aucun",
        main_zone="Système cardiovasculaire",
        secondary_zones="Fléchisseurs de la hanche, Mollets",
        joint_impact="Moyen",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Courir sur place en montant les genoux, dos droit",
        common_mistakes="Se pencher en arrière pendant la course",
        progression="High knees rapides avec résistance",
        regression="Montées de genoux marchées",
        contraindications="Douleur de hanche, NO_JUMP",
        tags="Cardio, Vitesse",
        video_url="https://youtube.com/shorts/0X0Q8wKLEfo"
    ),
    Exercise(
        code_id="CAR-005",
        name="Skater Jumps",
        family="Cardio",
        subfamily="Cardio latéral",
        discipline="Préparation physique",
        level="Intermédiaire",
        objective="Agilité latérale / Fessiers",
        material="Aucun",
        main_zone="Moyen fessier",
        secondary_zones="Quadriceps, Système cardiovasculaire",
        joint_impact="Moyen",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Sauter latéralement d'une jambe sur l'autre",
        common_mistakes="Perte d'équilibre à la réception",
        progression="Skater jumps amples et rapides",
        regression="Pas chassés latéraux",
        contraindications="Instabilité de cheville, NO_JUMP",
        tags="Cardio, Latéral, Agilité",
        video_url="https://youtube.com/shorts/qM5jviFhw9U"
    ),
    Exercise(
        code_id="MOB-001",
        name="World's Greatest Stretch",
        family="Mobilité",
        subfamily="Mobilité globale",
        discipline="Mobilité",
        level="Débutant",
        objective="Mobilité hanches et thoracique",
        material="Aucun",
        main_zone="Hanches",
        secondary_zones="Colonne thoracique, Ischio-jambiers",
        joint_impact="Faible",
        repetitions="5/côté",
        series="2",
        rest="45 s",
        instructions="Grande fente avant, poser le coude au sol, puis rotation vers le ciel",
        common_mistakes="Précipitation du mouvement",
        progression="World's Greatest stretch avec rotation ample",
        regression="Version simplifiée genou posé",
        contraindications="Aucune spécifique",
        tags="Mobilité, Échauffement",
        video_url="https://youtube.com/shorts/kSPS_HIQv8E"
    ),
    Exercise(
        code_id="MOB-002",
        name="Cat-Cow (Chat-Vache)",
        family="Mobilité",
        subfamily="Colonne vertébrale",
        discipline="Mobilité",
        level="Débutant",
        objective="Mobilité vertébrale",
        material="Aucun",
        main_zone="Colonne vertébrale",
        secondary_zones="Core",
        joint_impact="Faible",
        duration="60 s",
        series="2",
        rest="30 s",
        instructions="À quatre pattes, alterner dos rond et dos creusé",
        common_mistakes="Mouvement brusque au niveau cervical",
        progression="Cat-Cow avec pauses amples",
        regression="Amplitude réduite",
        contraindications="Douleur dorsale aiguë",
        tags="Mobilité, Dos, Douceur",
        video_url="https://youtube.com/shorts/2of247Kt0tU"
    ),
    Exercise(
        code_id="MOB-003",
        name="Mobilité des chevilles contre un mur",
        family="Mobilité",
        subfamily="Bas du corps",
        discipline="Mobilité",
        level="Débutant",
        objective="Dorsiflexion de cheville",
        material="Mur",
        main_zone="Chevilles",
        secondary_zones="Mollets",
        joint_impact="Faible",
        repetitions="10/jambe",
        series="2",
        rest="30 s",
        instructions="Pied à 10 cm du mur, avancer le genou pour toucher le mur",
        common_mistakes="Décoller le talon du sol",
        progression="Mobilisation cheville avec élastique",
        regression="Pied plus près du mur",
        contraindications="Entorse récente",
        tags="Mobilité, Chevilles",
        video_url="https://youtube.com/shorts/sP8HXhZ7iE8"
    ),
    Exercise(
        code_id="MOB-004",
        name="Ouverture thoracique (T-Spine rotation)",
        family="Mobilité",
        subfamily="Haut du corps",
        discipline="Mobilité",
        level="Débutant",
        objective="Mobilité thoracique",
        material="Tapis",
        main_zone="Colonne thoracique",
        secondary_zones="Épaules",
        joint_impact="Faible",
        repetitions="10/côté",
        series="2",
        rest="30 s",
        instructions="Allongé sur le côté genoux fléchis à 90°, ouvrir le bras en grand",
        common_mistakes="Décoller les genoux du sol pendant la rotation",
        progression="Rotation thoracique assise",
        regression="Amplitude partielle",
        contraindications="Douleur d'épaule",
        tags="Mobilité, Dos haut",
        video_url="https://youtube.com/shorts/cncdlzYmbxg"
    ),
    Exercise(
        code_id="MOB-005",
        name="Mobilité des hanches 90/90",
        family="Mobilité",
        subfamily="Bas du corps",
        discipline="Mobilité",
        level="Intermédiaire",
        objective="Rotation interne/externe des hanches",
        material="Aucun",
        main_zone="Hanches",
        secondary_zones="Fessiers",
        joint_impact="Faible",
        duration="60 s",
        series="2",
        rest="30 s",
        instructions="Assis au sol, jambes fléchies à 90°, basculer les genoux de gauche à droite",
        common_mistakes="S'aider des mains de manière excessive",
        progression="90/90 sans les mains",
        regression="Amplitude réduite avec appui arrière",
        contraindications="Douleur de hanche",
        tags="Mobilité, Hanches",
        video_url="https://youtube.com/shorts/fDC2KC1XqY8"
    ),
    Exercise(
        code_id="FB-001",
        name="Thruster haltères",
        family="Full Body",
        subfamily="Poussée & Bas du corps",
        discipline="Musculation",
        level="Intermédiaire",
        objective="Puissance globale / Métabolique",
        material="Haltères",
        main_zone="Corps entier",
        secondary_zones="Quadriceps, Deltoïdes, Core",
        joint_impact="Élevé",
        repetitions="10",
        series="3",
        rest="90 s",
        instructions="Squat complet suivi d'une poussée explosive des bras",
        common_mistakes="Pousser avec les bras avant d'avoir fini l'extension",
        progression="Thruster lourd",
        regression="Thruster au poids du corps",
        contraindications="Lombalgie ou épaule douloureuse",
        tags="Full Body, Métabolique",
        video_url="https://youtube.com/shorts/M2LaTuuOyv4"
    ),
    Exercise(
        code_id="FB-002",
        name="Kettlebell Swing",
        family="Full Body",
        subfamily="Chaîne postérieure",
        discipline="Haltérophilie",
        level="Débutant",
        objective="Explosivité / Chaîne postérieure",
        material="Kettlebell",
        main_zone="Fessiers",
        secondary_zones="Ischio-jambiers, Lombaire, Épaules",
        joint_impact="Moyen",
        repetitions="15",
        series="3",
        rest="60 s",
        instructions="Charnière de hanche, propulser le kettlebell par l'impulsion des fessiers",
        common_mistakes="Squatter le mouvement au lieu de charnière",
        progression="Kettlebell swing lourd ou américain",
        regression="Kettlebell deadlift simple",
        contraindications="Lombalgie aiguë",
        tags="Full Body, Puissance",
        video_url="https://youtube.com/shorts/3lMRRqyTuK8"
    ),
    Exercise(
        code_id="FB-003",
        name="Burpees avec pompe complète",
        family="Full Body",
        subfamily="Cardio / Renforcement",
        discipline="Préparation physique",
        level="Avancé",
        objective="Conditionnement total",
        material="Aucun",
        main_zone="Corps entier",
        secondary_zones="Pectoraux, Quadriceps, Core",
        joint_impact="Élevé",
        repetitions="10",
        series="3",
        rest="90 s",
        instructions="Descendre en squat, poser les mains, faire une pompe, ramener et sauter",
        common_mistakes="Affaissement des lombaires en remontant",
        progression="Burpees avec saut sur box",
        regression="Burpees sans pompe",
        contraindications="Douleur poignets ou épaules, NO_JUMP",
        tags="Full Body, Intense",
        video_url="https://youtube.com/shorts/QDttLyGKhQk"
    ),
    Exercise(
        code_id="FB-004",
        name="Manmaker (Haltères)",
        family="Full Body",
        subfamily="Mixte force & cardio",
        discipline="Musculation",
        level="Avancé",
        objective="Force fonctionnelle totale",
        material="Haltères",
        main_zone="Corps entier",
        secondary_zones="Dos, Pectoraux, Épaules, Jambes",
        joint_impact="Élevé",
        repetitions="6",
        series="3",
        rest="120 s",
        instructions="Pompe sur haltères, rowing par bras, saut groupé, épaulé-jeté",
        common_mistakes="Vouloir aller trop vite au détriment de la posture",
        progression="Manmaker lourd",
        regression="Manmaker sans la charge",
        contraindications="Lombalgie ou fatigue excessive",
        tags="Full Body, Avancé",
        video_url="https://youtube.com/shorts/DjTryuo3T6s"
    ),
    Exercise(
        code_id="FB-005",
        name="Clean and Press avec kettlebell",
        family="Full Body",
        subfamily="Combinés / Poussée verticale",
        discipline="Haltérophilie",
        level="Intermédiaire",
        objective="Puissance globale",
        material="Kettlebell",
        main_zone="Corps entier",
        secondary_zones="Épaules, Fessiers, Quadriceps",
        joint_impact="Moyen",
        repetitions="8/bras",
        series="3",
        rest="90 s",
        instructions="Amener le kettlebell à l'épaule par un tirage explosif des hanches, puis développer",
        common_mistakes="Tirer avec le bras au lieu de projeter avec les hanches",
        progression="Clean and Press lourd avec barre",
        regression="Épaulé simple sans développé",
        contraindications="Douleur poignet ou épaule",
        tags="Full Body, Puissance",
        video_url="https://youtube.com/shorts/h4KafmF7Xwc"
    ),
    Exercise(
        code_id="BOX-001",
        name="Shadow Boxe 5 (jab, cross, hook, uppercut)",
        family="Boxe",
        subfamily="Frappes de base",
        discipline="Boxe",
        level="Débutant",
        objective="Cardio / Coordination",
        material="Aucun",
        main_zone="Épaules",
        secondary_zones="Core, Système cardiovasculaire",
        joint_impact="Faible",
        duration="60 s",
        series="3",
        rest="45 s",
        instructions="Garde haute, lancer le Jab puis le Cross en pivotant le pied",
        common_mistakes="Tendre complètement le coude de manière brusque",
        progression="Shadow boxe avec petits haltères",
        regression="Shadow boxe lent face à un miroir",
        contraindications="Douleur au coude",
        tags="Boxe, Cardio, Technique",
        video_url="https://youtube.com/shorts/LMhVqtK3p_Y"
    ),
    Exercise(
        code_id="BOX-002",
        name="Crochets et Uppercuts en shadow",
        family="Boxe",
        subfamily="Frappes circulaires",
        discipline="Boxe",
        level="Intermédiaire",
        objective="Puissance rotationnelle / Cardio",
        material="Aucun",
        main_zone="Core / Obliques",
        secondary_zones="Épaules, Hanches",
        joint_impact="Moyen",
        duration="60 s",
        series="3",
        rest="45 s",
        instructions="Pivoter sur les appuis pour lancer crochets et uppercuts",
        common_mistakes="Oublier la rotation du bassin et des pieds",
        progression="Shadow avec résistance élastique",
        regression="Shadow direct uniquement",
        contraindications="Douleur lombaire par torsion sèche",
        tags="Boxe, Obliques, Dynamique",
        video_url="https://youtube.com/shorts/a1PAFI8OYis"
    ),
    Exercise(
        code_id="BOX-003",
        name="Esquives rotatives (Slip & Roll)",
        family="Boxe",
        subfamily="Défense",
        discipline="Boxe",
        level="Intermédiaire",
        objective="Agilité / Coordination défensive",
        material="Aucun",
        main_zone="Core",
        secondary_zones="Jambes, Hanches",
        joint_impact="Faible",
        duration="60 s",
        series="3",
        rest="45 s",
        instructions="Fléchir les jambes et pivoter le buste en 'U' pour esquiver",
        common_mistakes="Pencher le buste en avant sans plier les genoux",
        progression="Esquives suivies d'une contre-attaque",
        regression="Esquives lentes sur place",
        contraindications="Douleur cervicale",
        tags="Boxe, Défense, Mobilité",
        video_url="https://youtube.com/shorts/EWykTUVMMpY"
    ),
    Exercise(
        code_id="BOX-004",
        name="Shadow Boxe avec déplacements (Footwork)",
        family="Boxe",
        subfamily="Déplacements",
        discipline="Boxe",
        level="Avancé",
        objective="Jambes / Agilité en combat",
        material="Aucun",
        main_zone="Jambes",
        secondary_zones="Système cardiovasculaire, Core",
        joint_impact="Moyen",
        duration="90 s",
        series="3",
        rest="60 s",
        instructions="Se déplacer en pas chassés, avancer et reculer en gardant toujours sa garde",
        common_mistakes="Croiser les pieds pendant les déplacements latéraux",
        progression="Shadow avec frappes en mouvement",
        regression="Déplacements simples sur une ligne",
        contraindications="Instabilité de cheville",
        tags="Boxe, Agilité, Avancé",
        video_url="https://youtube.com/shorts/L30WFJ7d1BA"
    )
]


class ExerciseService:
    """
    Service d'accès et de gestion des 49 exercices réels.
    """

    @classmethod
    async def get_all_exercises(cls) -> List[Exercise]:
        """
        Récupère les 49 exercices depuis Supabase ou fallback local.
        """
        client = get_supabase_client()
        if client is None:
            return DEFAULT_EXERCISES

        try:
            response = client.table("exercises").select("*").execute()
            if response.data and len(response.data) > 0:
                return [Exercise(**row) for row in response.data]
            return DEFAULT_EXERCISES
        except Exception as e:
            logger.error(f"Erreur Supabase get_all_exercises: {e}")
            return DEFAULT_EXERCISES

    @classmethod
    async def get_exercises_by_family(cls, family: str) -> List[Exercise]:
        """
        Filtre les exercices par famille (Force, Gainage, Cardio, Mobilité, Full Body, Boxe).
        """
        all_exs = await cls.get_all_exercises()
        return [ex for ex in all_exs if ex.family and ex.family.lower() == family.lower()]

    @classmethod
    async def seed_exercises_to_supabase(cls) -> int:
        """
        Injecte les 49 exercices réels dans la base Supabase.
        """
        client = get_supabase_client()
        if client is None:
            logger.warning("Supabase non configuré.")
            return 0

        inserted_count = 0
        for ex in DEFAULT_EXERCISES:
            try:
                data = ex.model_dump(exclude_none=True)
                client.table("exercises").upsert(data, on_conflict="code_id").execute()
                inserted_count += 1
            except Exception as e:
                logger.warning(f"Erreur insertion '{ex.name}': {e}")

        logger.info(f"✅ {inserted_count}/49 exercices injectés dans Supabase.")
        return inserted_count
