import logging
from typing import List, Optional
from app.core.supabase import get_supabase_client
from app.models.schemas import Exercise

logger = logging.getLogger(__name__)

# ==============================================================================
# CATALOGUE COMPLET DES 49 EXERCICES DE BASE (Coaching_IA_Base_V1)
# ==============================================================================
DEFAULT_EXERCISES: List[Exercise] = [
    Exercise(
        code_id="STR-001",
        name="Air Squat",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Force / Endurance",
        material="Aucun",
        main_zone="Quadriceps",
        secondary_zones="Fessiers, Core",
        joint_impact="Faible",
        repetitions="15",
        series="3",
        rest="60 s",
        instructions="Descendre jusqu'Ã  cuisses parallÃ¨les, talons au sol",
        common_mistakes="Genoux qui rentrent, dos rond",
        progression="Goblet Squat",
        regression="Box Squat",
        contraindications="Douleur ou instabilitÃ©",
        tags="Force, DÃ©butant, Maison, Full Body",
        video_url="https://youtube.com/shorts/8voSXZyTp2A"
    ),
    Exercise(
        code_id="STR-002",
        name="Goblet Squat",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Force",
        material="HaltÃ¨re/Kettlebell",
        main_zone="Quadriceps",
        secondary_zones="Fessiers, Core",
        joint_impact="Moyen",
        repetitions="12",
        series="4",
        rest="90 s",
        instructions="Garder le poids proche de la poitrine",
        common_mistakes="Pencher le buste",
        progression="Front Squat",
        regression="Air Squat",
        contraindications="Lombalgie aiguÃ«",
        tags="Force, HaltÃ¨re",
        video_url="https://youtube.com/shorts/Bt8lsQStck0"
    ),
    Exercise(
        code_id="STR-003",
        name="Bulgarian Split Squat",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Force unilatÃ©rale",
        material="Banc + HaltÃ¨res",
        main_zone="Quadriceps",
        secondary_zones="Fessiers",
        joint_impact="Moyen",
        repetitions="10/jambe",
        series="3",
        rest="90 s",
        instructions="Genou alignÃ© avec le pied",
        common_mistakes="Perte d'Ã©quilibre",
        progression="Avec charge",
        regression="Fente arriÃ¨re",
        contraindications="Douleur importante au genou",
        tags="UnilatÃ©ral",
        video_url="https://youtube.com/shorts/uBSoEWZu07k"
    ),
    Exercise(
        code_id="STR-004",
        name="Walking Lunge",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Endurance musculaire",
        material="Aucun",
        main_zone="Quadriceps",
        secondary_zones="Fessiers",
        joint_impact="Moyen",
        repetitions="20 pas",
        series="3",
        rest="60 s",
        instructions="Faire de grandes foulÃ©es",
        common_mistakes="Genou avant dÃ©passe excessivement",
        progression="Avec haltÃ¨res",
        regression="Fente statique",
        contraindications="Douleur genou",
        tags="Fentes",
        video_url="https://youtube.com/shorts/Agmpy7Pj1Nw"
    ),
    Exercise(
        code_id="STR-005",
        name="Glute Bridge",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Activation fessiers",
        material="Aucun",
        main_zone="Fessiers",
        secondary_zones="Ischio-jambiers",
        joint_impact="Faible",
        repetitions="20",
        series="3",
        rest="45 s",
        instructions="Monter les hanches complÃ¨tement",
        common_mistakes="Hyperextension lombaire",
        progression="Hip Thrust",
        regression="Bridge partiel",
        contraindications="Aucune",
        tags="Fessiers, PrÃ©vention",
        video_url="https://youtube.com/shorts/RrU4zx4ysnI"
    ),
    Exercise(
        code_id="STR-006",
        name="Hip Thrust",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Puissance hanches",
        material="Barre",
        main_zone="Fessiers",
        secondary_zones="Ischios",
        joint_impact="Moyen",
        repetitions="10",
        series="4",
        rest="90 s",
        instructions="Contracter les fessiers en haut",
        common_mistakes="Extension lombaire",
        progression="Plus lourd",
        regression="Glute Bridge",
        contraindications="Douleur lombaire",
        tags="Puissance",
        video_url="https://youtube.com/shorts/CvuVYMFd11g"
    ),
    Exercise(
        code_id="STR-007",
        name="Romanian Deadlift",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="ChaÃ®ne postÃ©rieure",
        material="Barre/HaltÃ¨res",
        main_zone="Ischio-jambiers",
        secondary_zones="Lombaires, Fessiers",
        joint_impact="Moyen",
        repetitions="10",
        series="4",
        rest="90 s",
        instructions="Garder le dos neutre",
        common_mistakes="Arrondir le dos",
        progression="Deadlift",
        regression="Good Morning sans charge",
        contraindications="Lombalgie aiguÃ«",
        tags="Ischios",
        video_url="https://youtube.com/shorts/_TchJLlBO-4"
    ),
    Exercise(
        code_id="STR-008",
        name="Step Up",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Force fonctionnelle",
        material="Banc",
        main_zone="Quadriceps",
        secondary_zones="Fessiers",
        joint_impact="Faible",
        repetitions="12/jambe",
        series="3",
        rest="60 s",
        instructions="Pousser avec la jambe sur le banc",
        common_mistakes="Prendre de l'Ã©lan avec la jambe arriÃ¨re",
        progression="Avec haltÃ¨res",
        regression="Banc plus bas",
        contraindications="Douleur genou",
        tags="Fonctionnel",
        video_url="https://youtube.com/shorts/TG3xUe-UvCQ"
    ),
    Exercise(
        code_id="STR-009",
        name="Wall Sit",
        family="Force",
        subfamily="Bas du corps",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Endurance",
        material="Mur",
        main_zone="Quadriceps",
        secondary_zones="Core",
        joint_impact="Faible",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Garder les cuisses parallÃ¨les",
        common_mistakes="Monter ou descendre trop",
        progression="Plus long",
        regression="Angle moins fermÃ©",
        contraindications="Douleur rotulienne",
        tags="IsomÃ©trique",
        video_url="https://youtube.com/shorts/mDdLC-yKudY"
    ),
    Exercise(
        code_id="STR-010",
        name="Box Jump",
        family="Force",
        subfamily="Bas du corps",
        discipline="Cross Training",
        level="AvancÃ©",
        objective="ExplosivitÃ©",
        material="Box",
        main_zone="Quadriceps",
        secondary_zones="Mollets",
        joint_impact="Ã‰levÃ©",
        repetitions="8",
        series="4",
        rest="90 s",
        instructions="Atterrir en douceur",
        common_mistakes="Genoux en valgus",
        progression="Box plus haute",
        regression="Squat Jump",
        contraindications="ProblÃ¨mes de genoux/chevilles, NO_JUMP",
        tags="ExplosivitÃ©",
        video_url="https://youtube.com/shorts/vBZ9N6KnLI8"
    ),
    Exercise(
        code_id="UPP-001",
        name="Pompes classiques",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Force / Endurance",
        material="Aucun",
        main_zone="Pectoraux",
        secondary_zones="Triceps, Ã‰paules, Core",
        joint_impact="Faible",
        repetitions="12",
        series="3",
        rest="60 s",
        instructions="Corps gainÃ©, poitrine proche du sol",
        common_mistakes="Hanches qui tombent, coudes trop ouverts",
        progression="Pompes dÃ©clinÃ©es",
        regression="Pompes sur genoux",
        contraindications="Douleur aiguÃ« Ã  l'Ã©paule",
        tags="Push, Maison, DÃ©butant",
        video_url="https://youtube.com/shorts/n8PJC6yo_1o"
    ),
    Exercise(
        code_id="UPP-002",
        name="DÃ©veloppÃ© couchÃ©",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Force maximale",
        material="Barre",
        main_zone="Pectoraux",
        secondary_zones="Triceps, DeltoÃ¯des",
        joint_impact="Moyen",
        repetitions="8",
        series="4",
        rest="120 s",
        instructions="Omoplates serrÃ©es, pieds ancrÃ©s",
        common_mistakes="Rebondir sur la poitrine",
        progression="Plus lourd",
        regression="DÃ©veloppÃ© haltÃ¨res",
        contraindications="Blessure Ã©paule",
        tags="Salle, Force",
        video_url="https://youtube.com/shorts/Jc06xowWeI4"
    ),
    Exercise(
        code_id="UPP-003",
        name="DÃ©veloppÃ© haltÃ¨res",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Hypertrophie",
        material="HaltÃ¨res",
        main_zone="Pectoraux",
        secondary_zones="Triceps",
        joint_impact="Faible",
        repetitions="12",
        series="3",
        rest="90 s",
        instructions="Mouvement contrÃ´lÃ©",
        common_mistakes="Amplitude incomplÃ¨te",
        progression="Banc inclinÃ©",
        regression="Pompes",
        contraindications="Ã‰paule instable",
        tags="HaltÃ¨res",
        video_url="https://youtube.com/shorts/xoTdvzKWib8"
    ),
    Exercise(
        code_id="UPP-004",
        name="DÃ©veloppÃ© militaire",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Force Ã©paules",
        material="Barre",
        main_zone="DeltoÃ¯des",
        secondary_zones="Triceps, Core",
        joint_impact="Moyen",
        repetitions="8",
        series="4",
        rest="90 s",
        instructions="Contracter les abdos",
        common_mistakes="Hyperlordose",
        progression="Push Press",
        regression="DÃ©veloppÃ© haltÃ¨res assis",
        contraindications="Douleur cervicale",
        tags="Ã‰paules",
        video_url="https://youtube.com/shorts/TH8ovIkkkLk"
    ),
    Exercise(
        code_id="UPP-005",
        name="DÃ©veloppÃ© Arnold",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Hypertrophie Ã©paules",
        material="HaltÃ¨res",
        main_zone="DeltoÃ¯des",
        secondary_zones="Triceps",
        joint_impact="Faible",
        repetitions="10",
        series="3",
        rest="75 s",
        instructions="Rotation fluide",
        common_mistakes="Rotation trop rapide",
        progression="Plus lourd",
        regression="DÃ©veloppÃ© haltÃ¨res",
        contraindications="Douleur Ã©paule",
        tags="Arnold Press",
        video_url="https://youtube.com/shorts/KYYNNj4v2J0"
    ),
    Exercise(
        code_id="UPP-006",
        name="Dips",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Musculation",
        level="AvancÃ©",
        objective="Force",
        material="Barres parallÃ¨les",
        main_zone="Triceps",
        secondary_zones="Pectoraux",
        joint_impact="Ã‰levÃ©",
        repetitions="10",
        series="4",
        rest="90 s",
        instructions="Descendre sous les 90Â° sans douleur",
        common_mistakes="Ã‰paules qui remontent",
        progression="Dips lestÃ©s",
        regression="Bench Dips",
        contraindications="Ã‰paule instable",
        tags="Triceps",
        video_url="https://youtube.com/shorts/CrbIq-T-h8I"
    ),
    Exercise(
        code_id="UPP-007",
        name="Push Press",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="HaltÃ©rophilie",
        level="AvancÃ©",
        objective="Puissance",
        material="Barre",
        main_zone="DeltoÃ¯des",
        secondary_zones="Triceps, Jambes",
        joint_impact="Moyen",
        repetitions="6",
        series="5",
        rest="120 s",
        instructions="Utiliser l'impulsion des jambes",
        common_mistakes="Pousser uniquement avec les bras",
        progression="Plus lourd",
        regression="DÃ©veloppÃ© militaire",
        contraindications="Lombalgie aiguÃ«",
        tags="Puissance",
        video_url="https://youtube.com/shorts/VaIDqmZBkpc"
    ),
    Exercise(
        code_id="UPP-008",
        name="Landmine Press",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Force fonctionnelle",
        material="Barre Landmine",
        main_zone="DeltoÃ¯des",
        secondary_zones="Pectoraux, Core",
        joint_impact="Faible",
        repetitions="10/bras",
        series="3",
        rest="75 s",
        instructions="Pousser dans l'axe",
        common_mistakes="Rotation du tronc",
        progression="Debout unilatÃ©ral",
        regression="DÃ©veloppÃ© haltÃ¨res",
        contraindications="Aucune spÃ©cifique",
        tags="Fonctionnel",
        video_url="https://youtube.com/shorts/Iu5pYQEkj38"
    ),
    Exercise(
        code_id="UPP-009",
        name="Pompes explosives",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="PrÃ©paration physique",
        level="AvancÃ©",
        objective="ExplosivitÃ©",
        material="Aucun",
        main_zone="Pectoraux",
        secondary_zones="Triceps",
        joint_impact="Moyen",
        repetitions="8",
        series="5",
        rest="90 s",
        instructions="DÃ©coller les mains rapidement",
        common_mistakes="Mauvaise rÃ©ception",
        progression="Pompes claquÃ©es",
        regression="Pompes classiques",
        contraindications="Poignets douloureux",
        tags="ExplosivitÃ©",
        video_url="https://youtube.com/shorts/2JxSJyt_IMk"
    ),
    Exercise(
        code_id="UPP-010",
        name="Pike Push-Up",
        family="Force",
        subfamily="Haut du corps poussÃ©e",
        discipline="Calisthenics",
        level="IntermÃ©diaire",
        objective="Force verticale",
        material="Aucun",
        main_zone="DeltoÃ¯des",
        secondary_zones="Triceps",
        joint_impact="Moyen",
        repetitions="10",
        series="3",
        rest="60 s",
        instructions="Descendre la tÃªte entre les mains",
        common_mistakes="Dos arrondi",
        progression="Handstand Push-Up",
        regression="Pompes inclinÃ©es",
        contraindications="Douleur cervicale",
        tags="Poids du corps",
        video_url="https://youtube.com/shorts/UalsVVpBacw"
    ),
    Exercise(
        code_id="THC-001",
        name="Tractions pronination (Pull-ups)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Calisthenics",
        level="AvancÃ©",
        objective="Force dos / Largeur",
        material="Barre de traction",
        main_zone="Grand dorsal",
        secondary_zones="Biceps, Grand rond, TrapÃ¨zes",
        joint_impact="Moyen",
        repetitions="6",
        series="3",
        rest="90 s",
        instructions="Prise un peu plus large que les Ã©paules, tirer les coudes vers le bas",
        common_mistakes="Balancement du corps, amplitude incomplÃ¨te",
        progression="Tractions lestÃ©es",
        regression="Tractions assistÃ©es avec Ã©lastique",
        contraindications="Douleur aiguÃ« Ã  l'Ã©paule ou au coude",
        tags="Dos, Largeur, AvancÃ©",
        video_url="https://youtube.com/shorts/ym1V5H35IpA"
    ),
    Exercise(
        code_id="THC-002",
        name="Tractions supination (Chin-ups)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Calisthenics",
        level="IntermÃ©diaire",
        objective="Force dos et biceps",
        material="Barre de traction",
        main_zone="Grand dorsal",
        secondary_zones="Biceps brachial",
        joint_impact="Moyen",
        repetitions="8",
        series="3",
        rest="90 s",
        instructions="Paumes de mains vers soi, prise largeur d'Ã©paules",
        common_mistakes="Ne pas tendre complÃ¨tement les bras en bas",
        progression="Tractions supination lestÃ©es",
        regression="Tractions australiennes",
        contraindications="Tendinite au coude",
        tags="Biceps, Dos, IntermÃ©diaire",
        video_url="https://youtube.com/shorts/Oi3bW9nQmGI"
    ),
    Exercise(
        code_id="THC-003",
        name="Tirage horizontal unilatÃ©ral aux haltÃ¨res (Rowing)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Musculation",
        level="DÃ©butant",
        objective="Ã‰paisseur du dos",
        material="Banc et HaltÃ¨re",
        main_zone="Grand dorsal",
        secondary_zones="RomboÃ¯des, Biceps, TrapÃ¨zes",
        joint_impact="Faible",
        repetitions="10/bras",
        series="3",
        rest="75 s",
        instructions="Un genou et une main sur le banc, tirer l'haltÃ¨re vers la hanche",
        common_mistakes="Rotation excessive du tronc, tirer avec le bras",
        progression="Rowing barre lourd",
        regression="Rowing buste penchÃ© lÃ©ger",
        contraindications="Lombalgie sensible",
        tags="Dos, UnilatÃ©ral, Maison",
        video_url="https://youtube.com/shorts/vu_YDt9nGv4"
    ),
    Exercise(
        code_id="THC-004",
        name="Rowing buste penchÃ© aux haltÃ¨res",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Ã‰paisseur globale du dos",
        material="HaltÃ¨res",
        main_zone="Grand dorsal",
        secondary_zones="RomboÃ¯des, Ã‰recteurs du rachis",
        joint_impact="Moyen",
        repetitions="10",
        series="3",
        rest="90 s",
        instructions="Buste penchÃ© Ã  45Â°, dos plat",
        common_mistakes="Arrondir le dos pendant le tirage",
        progression="Rowing barre olympique",
        regression="Rowing sur banc inclinÃ©",
        contraindications="Hernie discale",
        tags="Dos, Ã‰paisseur",
        video_url="https://youtube.com/shorts/dpYI8K6e-jE"
    ),
    Exercise(
        code_id="THC-005",
        name="Tractions australiennes (Inverted Row)",
        family="Force",
        subfamily="Haut du corps tirage",
        discipline="Calisthenics",
        level="DÃ©butant",
        objective="Renforcement dos accessible",
        material="Barre fixe basse ou TRX",
        main_zone="Grand dorsal",
        secondary_zones="RomboÃ¯des, Biceps",
        joint_impact="Faible",
        repetitions="12",
        series="3",
        rest="60 s",
        instructions="Corps alignÃ© sous la barre, tirer la poitrine contre la barre",
        common_mistakes="Laisser creuser les hanches",
        progression="Tractions classiques",
        regression="Tractions australiennes jambes flÃ©chies",
        contraindications="Aucune spÃ©cifique",
        tags="DÃ©butant, Maison, TRX",
        video_url="https://youtube.com/shorts/qfsEK96Px-E"
    ),
    Exercise(
        code_id="COR-001",
        name="Gainage planche forearm (Plank)",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="DÃ©butant",
        objective="StabilitÃ© lombo-abdominale",
        material="Aucun",
        main_zone="Grand droit de l'abdomen",
        secondary_zones="Transverse, Ã‰paules, Fessiers",
        joint_impact="Faible",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Appui sur les avant-bras et pointes de pieds, bassin en rÃ©troversion",
        common_mistakes="Fesses trop hautes ou bassin qui s'affaisse",
        progression="Planche dynamique / sur une main",
        regression="Planche sur les genoux",
        contraindications="Lombalgie aiguÃ« en extension",
        tags="Core, Maison, DÃ©butant",
        video_url="https://youtube.com/shorts/E-PBfoIMc-0"
    ),
    Exercise(
        code_id="COR-002",
        name="Gainage latÃ©ral (Side Plank)",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="IntermÃ©diaire",
        objective="StabilitÃ© latÃ©rale / Obliques",
        material="Aucun",
        main_zone="Obliques",
        secondary_zones="CarrÃ© des lombaires, Moyen fessier",
        joint_impact="Faible",
        duration="30 s/cÃ´tÃ©",
        series="3",
        rest="45 s",
        instructions="Appui sur l'avant-bras latÃ©ral, alignement parfait",
        common_mistakes="Hanches qui piquent vers le sol",
        progression="Gainage latÃ©ral avec Ã©lÃ©vation de jambe",
        regression="Gainage latÃ©ral sur les genoux",
        contraindications="Douleur Ã  l'Ã©paule d'appui",
        tags="Core, Obliques, UnilatÃ©ral",
        video_url="https://youtube.com/shorts/eZQRj1yG-gY"
    ),
    Exercise(
        code_id="COR-003",
        name="Bird Dog (QuadrupÃ¨de)",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="DÃ©butant",
        objective="StabilitÃ© rachidienne / Posture",
        material="Aucun",
        main_zone="Ã‰recteurs du rachis",
        secondary_zones="Fessiers, Core",
        joint_impact="Faible",
        repetitions="10/cÃ´tÃ©",
        series="3",
        rest="60 s",
        instructions="Ã€ quatre pattes, tendre bras droit et jambe gauche sans bouger le bassin",
        common_mistakes="Rotation du bassin lors de l'extension",
        progression="Bird Dog avec rÃ©sistance Ã©lastique",
        regression="Extension unilatÃ©rale bras seul",
        contraindications="Aucune spÃ©cifique",
        tags="Core, SantÃ© du dos, DÃ©butant",
        video_url="https://youtube.com/shorts/vtwhC3tfVow"
    ),
    Exercise(
        code_id="COR-004",
        name="Dead Bug",
        family="Gainage",
        subfamily="Core",
        discipline="Calisthenics",
        level="DÃ©butant",
        objective="ContrÃ´le lombo-pelvien",
        material="Aucun",
        main_zone="Transverse de l'abdomen",
        secondary_zones="FlÃ©chisseurs de la hanche",
        joint_impact="Faible",
        repetitions="10/cÃ´tÃ©",
        series="3",
        rest="60 s",
        instructions="AllongÃ© sur le dos, bras levÃ©s, genoux Ã  90Â°",
        common_mistakes="Lombales qui se dÃ©collent du sol",
        progression="Dead Bug avec charge aux mains",
        regression="Dead Bug jambes flÃ©chies",
        contraindications="Douleur lombaire",
        tags="Core, Posture, Abdominaux",
        video_url="https://youtube.com/shorts/5c-vucY3beU"
    ),
    Exercise(
        code_id="COR-005",
        name="Mountain Climbers",
        family="Gainage",
        subfamily="Core / Cardio",
        discipline="PrÃ©paration physique",
        level="IntermÃ©diaire",
        objective="Cardio & Gainage dynamique",
        material="Aucun",
        main_zone="Core",
        secondary_zones="Ã‰paules, Quadriceps",
        joint_impact="Moyen",
        duration="45 s",
        series="3",
        rest="60 s",
        instructions="Position de pompe, ramener alternativement les genoux vers la poitrine",
        common_mistakes="Fesses qui montent trop haut",
        progression="Mountain climbers rapides ou croisÃ©s",
        regression="Mountain climbers lents en marchant",
        contraindications="Douleur aux poignets",
        tags="Core, Cardio, Dynamique",
        video_url="https://youtube.com/shorts/7W4JEfEKuC4"
    ),
    Exercise(
        code_id="CAR-001",
        name="Jumping Jacks",
        family="Cardio",
        subfamily="Cardio basique",
        discipline="PrÃ©paration physique",
        level="DÃ©butant",
        objective="Endurance cardiovasculaire",
        material="Aucun",
        main_zone="SystÃ¨me cardiovasculaire",
        secondary_zones="Mollets, Ã‰paules",
        joint_impact="Faible",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Sauter en Ã©cartant les jambes et en levant les bras",
        common_mistakes="Amorti trop lourd sur les articulations",
        progression="Jumping Jacks rythmÃ©s lestÃ©s",
        regression="Jumping Jacks sans saut",
        contraindications="Douleur aux genoux ou chevilles, NO_JUMP",
        tags="Cardio, Ã‰chauffement, Maison",
        video_url="https://youtube.com/shorts/yg3KQQn3QWg"
    ),
    Exercise(
        code_id="CAR-002",
        name="Corde Ã  sauter",
        family="Cardio",
        subfamily="Cardio dynamique",
        discipline="PrÃ©paration physique",
        level="IntermÃ©diaire",
        objective="AgilitÃ© / Cardio",
        material="Corde Ã  sauter",
        main_zone="SystÃ¨me cardiovasculaire",
        secondary_zones="Mollets, Avant-bras",
        joint_impact="Moyen",
        duration="60 s",
        series="3",
        rest="60 s",
        instructions="Sauts courts impulsÃ©s par les poignets",
        common_mistakes="Sauter trop haut ou utiliser les bras",
        progression="Double unders",
        regression="Sauts sur place sans corde",
        contraindications="Fasciite plantaire / Douleur tibiale, NO_JUMP",
        tags="Cardio, AgilitÃ©",
        video_url="https://youtube.com/shorts/iWa7KVOyAlU"
    ),
    Exercise(
        code_id="CAR-003",
        name="Burpees sans pompe",
        family="Cardio",
        subfamily="Cardio / Full Body",
        discipline="PrÃ©paration physique",
        level="IntermÃ©diaire",
        objective="Puissance aÃ©robie",
        material="Aucun",
        main_zone="Corps entier",
        secondary_zones="Quadriceps, Pectoraux, Core",
        joint_impact="Ã‰levÃ©",
        repetitions="10",
        series="3",
        rest="75 s",
        instructions="Passer accroupi, envoyer les pieds en arriÃ¨re, ramener et sauter",
        common_mistakes="Laisser creuser le dos en planche",
        progression="Burpees complets avec pompe et saut",
        regression="Burpees en marchant",
        contraindications="Lombalgie ou douleur poignets, NO_JUMP",
        tags="Cardio, IntensitÃ©",
        video_url="https://youtube.com/shorts/GJ2oJUrsm7s"
    ),
    Exercise(
        code_id="CAR-004",
        name="High Knees (Genoux montants)",
        family="Cardio",
        subfamily="Cardio dynamique",
        discipline="PrÃ©paration physique",
        level="DÃ©butant",
        objective="ExplosivitÃ© / Cardio",
        material="Aucun",
        main_zone="SystÃ¨me cardiovasculaire",
        secondary_zones="FlÃ©chisseurs de la hanche, Mollets",
        joint_impact="Moyen",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Courir sur place en montant les genoux, dos droit",
        common_mistakes="Se pencher en arriÃ¨re pendant la course",
        progression="High knees rapides avec rÃ©sistance",
        regression="MontÃ©es de genoux marchÃ©es",
        contraindications="Douleur de hanche, NO_JUMP",
        tags="Cardio, Vitesse",
        video_url="https://youtube.com/shorts/0X0Q8wKLEfo"
    ),
    Exercise(
        code_id="CAR-005",
        name="Skater Jumps",
        family="Cardio",
        subfamily="Cardio latÃ©ral",
        discipline="PrÃ©paration physique",
        level="IntermÃ©diaire",
        objective="AgilitÃ© latÃ©rale / Fessiers",
        material="Aucun",
        main_zone="Moyen fessier",
        secondary_zones="Quadriceps, SystÃ¨me cardiovasculaire",
        joint_impact="Moyen",
        duration="45 s",
        series="3",
        rest="45 s",
        instructions="Sauter latÃ©ralement d'une jambe sur l'autre",
        common_mistakes="Perte d'Ã©quilibre Ã  la rÃ©ception",
        progression="Skater jumps amples et rapides",
        regression="Pas chassÃ©s latÃ©raux",
        contraindications="InstabilitÃ© de cheville, NO_JUMP",
        tags="Cardio, LatÃ©ral, AgilitÃ©",
        video_url="https://youtube.com/shorts/qM5jviFhw9U"
    ),
    Exercise(
        code_id="MOB-001",
        name="World's Greatest Stretch",
        family="MobilitÃ©",
        subfamily="MobilitÃ© globale",
        discipline="MobilitÃ©",
        level="DÃ©butant",
        objective="MobilitÃ© hanches et thoracique",
        material="Aucun",
        main_zone="Hanches",
        secondary_zones="Colonne thoracique, Ischio-jambiers",
        joint_impact="Faible",
        repetitions="5/cÃ´tÃ©",
        series="2",
        rest="45 s",
        instructions="Grande fente avant, poser le coude au sol, puis rotation vers le ciel",
        common_mistakes="PrÃ©cipitation du mouvement",
        progression="World's Greatest stretch avec rotation ample",
        regression="Version simplifiÃ©e genou posÃ©",
        contraindications="Aucune spÃ©cifique",
        tags="MobilitÃ©, Ã‰chauffement",
        video_url="https://youtube.com/shorts/kSPS_HIQv8E"
    ),
    Exercise(
        code_id="MOB-002",
        name="Cat-Cow (Chat-Vache)",
        family="MobilitÃ©",
        subfamily="Colonne vertÃ©brale",
        discipline="MobilitÃ©",
        level="DÃ©butant",
        objective="MobilitÃ© vertÃ©brale",
        material="Aucun",
        main_zone="Colonne vertÃ©brale",
        secondary_zones="Core",
        joint_impact="Faible",
        duration="60 s",
        series="2",
        rest="30 s",
        instructions="Ã€ quatre pattes, alterner dos rond et dos creusÃ©",
        common_mistakes="Mouvement brusque au niveau cervical",
        progression="Cat-Cow avec pauses amples",
        regression="Amplitude rÃ©duite",
        contraindications="Douleur dorsale aiguÃ«",
        tags="MobilitÃ©, Dos, Douceur",
        video_url="https://youtube.com/shorts/2of247Kt0tU"
    ),
    Exercise(
        code_id="MOB-003",
        name="MobilitÃ© des chevilles contre un mur",
        family="MobilitÃ©",
        subfamily="Bas du corps",
        discipline="MobilitÃ©",
        level="DÃ©butant",
        objective="Dorsiflexion de cheville",
        material="Mur",
        main_zone="Chevilles",
        secondary_zones="Mollets",
        joint_impact="Faible",
        repetitions="10/jambe",
        series="2",
        rest="30 s",
        instructions="Pied Ã  10 cm du mur, avancer le genou pour toucher le mur",
        common_mistakes="DÃ©coller le talon du sol",
        progression="Mobilisation cheville avec Ã©lastique",
        regression="Pied plus prÃ¨s du mur",
        contraindications="Entorse rÃ©cente",
        tags="MobilitÃ©, Chevilles",
        video_url="https://youtube.com/shorts/sP8HXhZ7iE8"
    ),
    Exercise(
        code_id="MOB-004",
        name="Ouverture thoracique (T-Spine rotation)",
        family="MobilitÃ©",
        subfamily="Haut du corps",
        discipline="MobilitÃ©",
        level="DÃ©butant",
        objective="MobilitÃ© thoracique",
        material="Tapis",
        main_zone="Colonne thoracique",
        secondary_zones="Ã‰paules",
        joint_impact="Faible",
        repetitions="10/cÃ´tÃ©",
        series="2",
        rest="30 s",
        instructions="AllongÃ© sur le cÃ´tÃ© genoux flÃ©chis Ã  90Â°, ouvrir le bras en grand",
        common_mistakes="DÃ©coller les genoux du sol pendant la rotation",
        progression="Rotation thoracique assise",
        regression="Amplitude partielle",
        contraindications="Douleur d'Ã©paule",
        tags="MobilitÃ©, Dos haut",
        video_url="https://youtube.com/shorts/cncdlzYmbxg"
    ),
    Exercise(
        code_id="MOB-005",
        name="MobilitÃ© des hanches 90/90",
        family="MobilitÃ©",
        subfamily="Bas du corps",
        discipline="MobilitÃ©",
        level="IntermÃ©diaire",
        objective="Rotation interne/externe des hanches",
        material="Aucun",
        main_zone="Hanches",
        secondary_zones="Fessiers",
        joint_impact="Faible",
        duration="60 s",
        series="2",
        rest="30 s",
        instructions="Assis au sol, jambes flÃ©chies Ã  90Â°, basculer les genoux de gauche Ã  droite",
        common_mistakes="S'aider des mains de maniÃ¨re excessive",
        progression="90/90 sans les mains",
        regression="Amplitude rÃ©duite avec appui arriÃ¨re",
        contraindications="Douleur de hanche",
        tags="MobilitÃ©, Hanches",
        video_url="https://youtube.com/shorts/fDC2KC1XqY8"
    ),
    Exercise(
        code_id="FB-001",
        name="Thruster haltÃ¨res",
        family="Full Body",
        subfamily="PoussÃ©e & Bas du corps",
        discipline="Musculation",
        level="IntermÃ©diaire",
        objective="Puissance globale / MÃ©tabolique",
        material="HaltÃ¨res",
        main_zone="Corps entier",
        secondary_zones="Quadriceps, DeltoÃ¯des, Core",
        joint_impact="Ã‰levÃ©",
        repetitions="10",
        series="3",
        rest="90 s",
        instructions="Squat complet suivi d'une poussÃ©e explosive des bras",
        common_mistakes="Pousser avec les bras avant d'avoir fini l'extension",
        progression="Thruster lourd",
        regression="Thruster au poids du corps",
        contraindications="Lombalgie ou Ã©paule douloureuse",
        tags="Full Body, MÃ©tabolique",
        video_url="https://youtube.com/shorts/M2LaTuuOyv4"
    ),
    Exercise(
        code_id="FB-002",
        name="Kettlebell Swing",
        family="Full Body",
        subfamily="ChaÃ®ne postÃ©rieure",
        discipline="HaltÃ©rophilie",
        level="DÃ©butant",
        objective="ExplosivitÃ© / ChaÃ®ne postÃ©rieure",
        material="Kettlebell",
        main_zone="Fessiers",
        secondary_zones="Ischio-jambiers, Lombaire, Ã‰paules",
        joint_impact="Moyen",
        repetitions="15",
        series="3",
        rest="60 s",
        instructions="CharniÃ¨re de hanche, propulser le kettlebell par l'impulsion des fessiers",
        common_mistakes="Squatter le mouvement au lieu de charniÃ¨re",
        progression="Kettlebell swing lourd ou amÃ©ricain",
        regression="Kettlebell deadlift simple",
        contraindications="Lombalgie aiguÃ«",
        tags="Full Body, Puissance",
        video_url="https://youtube.com/shorts/3lMRRqyTuK8"
    ),
    Exercise(
        code_id="FB-003",
        name="Burpees avec pompe complÃ¨te",
        family="Full Body",
        subfamily="Cardio / Renforcement",
        discipline="PrÃ©paration physique",
        level="AvancÃ©",
        objective="Conditionnement total",
        material="Aucun",
        main_zone="Corps entier",
        secondary_zones="Pectoraux, Quadriceps, Core",
        joint_impact="Ã‰levÃ©",
        repetitions="10",
        series="3",
        rest="90 s",
        instructions="Descendre en squat, poser les mains, faire une pompe, ramener et sauter",
        common_mistakes="Affaissement des lombaires en remontant",
        progression="Burpees avec saut sur box",
        regression="Burpees sans pompe",
        contraindications="Douleur poignets ou Ã©paules, NO_JUMP",
        tags="Full Body, Intense",
        video_url="https://youtube.com/shorts/QDttLyGKhQk"
    ),
    Exercise(
        code_id="FB-004",
        name="Manmaker (HaltÃ¨res)",
        family="Full Body",
        subfamily="Mixte force & cardio",
        discipline="Musculation",
        level="AvancÃ©",
        objective="Force fonctionnelle totale",
        material="HaltÃ¨res",
        main_zone="Corps entier",
        secondary_zones="Dos, Pectoraux, Ã‰paules, Jambes",
        joint_impact="Ã‰levÃ©",
        repetitions="6",
        series="3",
        rest="120 s",
        instructions="Pompe sur haltÃ¨res, rowing par bras, saut groupÃ©, Ã©paulÃ©-jetÃ©",
        common_mistakes="Vouloir aller trop vite au dÃ©triment de la posture",
        progression="Manmaker lourd",
        regression="Manmaker sans la charge",
        contraindications="Lombalgie ou fatigue excessive",
        tags="Full Body, AvancÃ©",
        video_url="https://youtube.com/shorts/DjTryuo3T6s"
    ),
    Exercise(
        code_id="FB-005",
        name="Clean and Press avec kettlebell",
        family="Full Body",
        subfamily="CombinÃ©s / PoussÃ©e verticale",
        discipline="HaltÃ©rophilie",
        level="IntermÃ©diaire",
        objective="Puissance globale",
        material="Kettlebell",
        main_zone="Corps entier",
        secondary_zones="Ã‰paules, Fessiers, Quadriceps",
        joint_impact="Moyen",
        repetitions="8/bras",
        series="3",
        rest="90 s",
        instructions="Amener le kettlebell Ã  l'Ã©paule par un tirage explosif des hanches, puis dÃ©velopper",
        common_mistakes="Tirer avec le bras au lieu de projeter avec les hanches",
        progression="Clean and Press lourd avec barre",
        regression="Ã‰paulÃ© simple sans dÃ©veloppÃ©",
        contraindications="Douleur poignet ou Ã©paule",
        tags="Full Body, Puissance",
        video_url="https://youtube.com/shorts/h4KafmF7Xwc"
    ),
    Exercise(
        code_id="BOX-001",
        name="Shadow Boxe 5 (jab, cross, hook, uppercut)",
        family="Boxe",
        subfamily="Frappes de base",
        discipline="Boxe",
        level="DÃ©butant",
        objective="Cardio / Coordination",
        material="Aucun",
        main_zone="Ã‰paules",
        secondary_zones="Core, SystÃ¨me cardiovasculaire",
        joint_impact="Faible",
        duration="60 s",
        series="3",
        rest="45 s",
        instructions="Garde haute, lancer le Jab puis le Cross en pivotant le pied",
        common_mistakes="Tendre complÃ¨tement le coude de maniÃ¨re brusque",
        progression="Shadow boxe avec petits haltÃ¨res",
        regression="Shadow boxe lent face Ã  un miroir",
        contraindications="Douleur au coude",
        tags="Boxe, Cardio, Technique",
        video_url="https://youtube.com/shorts/LMhVqtK3p_Y"
    ),
    Exercise(
        code_id="BOX-002",
        name="Crochets et Uppercuts en shadow",
        family="Boxe",
        subfamily="Frappes circulaires",
        discipline="Boxe",
        level="IntermÃ©diaire",
        objective="Puissance rotationnelle / Cardio",
        material="Aucun",
        main_zone="Core / Obliques",
        secondary_zones="Ã‰paules, Hanches",
        joint_impact="Moyen",
        duration="60 s",
        series="3",
        rest="45 s",
        instructions="Pivoter sur les appuis pour lancer crochets et uppercuts",
        common_mistakes="Oublier la rotation du bassin et des pieds",
        progression="Shadow avec rÃ©sistance Ã©lastique",
        regression="Shadow direct uniquement",
        contraindications="Douleur lombaire par torsion sÃ¨che",
        tags="Boxe, Obliques, Dynamique",
        video_url="https://youtube.com/shorts/a1PAFI8OYis"
    ),
    Exercise(
        code_id="BOX-003",
        name="Esquives rotatives (Slip & Roll)",
        family="Boxe",
        subfamily="DÃ©fense",
        discipline="Boxe",
        level="IntermÃ©diaire",
        objective="AgilitÃ© / Coordination dÃ©fensive",
        material="Aucun",
        main_zone="Core",
        secondary_zones="Jambes, Hanches",
        joint_impact="Faible",
        duration="60 s",
        series="3",
        rest="45 s",
        instructions="FlÃ©chir les jambes et pivoter le buste en 'U' pour esquiver",
        common_mistakes="Pencher le buste en avant sans plier les genoux",
        progression="Esquives suivies d'une contre-attaque",
        regression="Esquives lentes sur place",
        contraindications="Douleur cervicale",
        tags="Boxe, DÃ©fense, MobilitÃ©",
        video_url="https://youtube.com/shorts/EWykTUVMMpY"
    ),
    Exercise(
        code_id="BOX-004",
        name="Shadow Boxe avec dÃ©placements (Footwork)",
        family="Boxe",
        subfamily="DÃ©placements",
        discipline="Boxe",
        level="AvancÃ©",
        objective="Jambes / AgilitÃ© en combat",
        material="Aucun",
        main_zone="Jambes",
        secondary_zones="SystÃ¨me cardiovasculaire, Core",
        joint_impact="Moyen",
        duration="90 s",
        series="3",
        rest="60 s",
        instructions="Se dÃ©placer en pas chassÃ©s, avancer et reculer en gardant toujours sa garde",
        common_mistakes="Croiser les pieds pendant les dÃ©placements latÃ©raux",
        progression="Shadow avec frappes en mouvement",
        regression="DÃ©placements simples sur une ligne",
        contraindications="InstabilitÃ© de cheville",
        tags="Boxe, AgilitÃ©, AvancÃ©",
        video_url="https://youtube.com/shorts/L30WFJ7d1BA"
    )
]


class ExerciseService:
    """
    Service d'accÃ¨s et de gestion des 49 exercices rÃ©els.
    """

    @classmethod
    async def get_all_exercises(cls) -> List[Exercise]:
        """
        RÃ©cupÃ¨re les 49 exercices depuis Supabase ou fallback local.
        """
        client = get_supabase_client()
        if client is None:
            return DEFAULT_EXERCISES

        try:
            response = client.table("exercises").select("*").execute()
            if response.data and len(response.data) > 0:
                return [Exercise(**row) for row in response.data]
            return DEFAULT_EXERCISES
        except Exception as e:
            logger.error(f"Erreur Supabase get_all_exercises: {e}")
            return DEFAULT_EXERCISES

    @classmethod
    async def get_exercises_by_family(cls, family: str) -> List[Exercise]:
        """
        Filtre les exercices par famille (Force, Gainage, Cardio, MobilitÃ©, Full Body, Boxe).
        """
        all_exs = await cls.get_all_exercises()
        return [ex for ex in all_exs if ex.family and ex.family.lower() == family.lower()]

    @classmethod
    async def seed_exercises_to_supabase(cls) -> int:
        """
        Injecte les 49 exercices rÃ©els dans la base Supabase.
        """
        client = get_supabase_client()
        if client is None:
            logger.warning("Supabase non configurÃ©.")
            return 0

        inserted_count = 0
        for ex in DEFAULT_EXERCISES:
            try:
                data = ex.model_dump(exclude_none=True)
                client.table("exercises").upsert(data, on_conflict="code_id").execute()
                inserted_count += 1
            except Exception as e:
                logger.warning(f"Erreur insertion '{ex.name}': {e}")

        logger.info(f"âœ… {inserted_count}/49 exercices injectÃ©s dans Supabase.")
        return inserted_count

