-- =============================================================================
-- Coaching IA V2 - Schéma Complet & 49 Exercices Réels (Coaching_IA_Base_V1)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Table: exercises
CREATE TABLE IF NOT EXISTS public.exercises (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    family TEXT NOT NULL,
    subfamily TEXT,
    discipline TEXT,
    level TEXT,
    objective TEXT,
    material TEXT,
    main_zone TEXT,
    secondary_zones TEXT,
    joint_impact TEXT,
    duration TEXT,
    repetitions TEXT,
    series TEXT,
    rest TEXT,
    instructions TEXT,
    common_mistakes TEXT,
    progression TEXT,
    regression TEXT,
    contraindications TEXT,
    tags TEXT,
    video_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS: Permettre la lecture publique
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read on exercises" ON public.exercises FOR SELECT USING (true);

-- 2. Vider et réinsérer les 49 exercices
TRUNCATE TABLE public.exercises CASCADE;

INSERT INTO public.exercises (
    code_id, name, family, subfamily, discipline, level, objective, material,
    main_zone, secondary_zones, joint_impact, duration, repetitions, series,
    rest, instructions, common_mistakes, progression, regression, contraindications, tags, video_url
) VALUES
('STR-001', 'Air Squat', 'Force', 'Bas du corps', 'Musculation', 'Débutant', 'Force / Endurance', 'Aucun', 'Quadriceps', 'Fessiers, Core', 'Faible', NULL, '15', '3', '60 s', 'Descendre jusqu''à cuisses parallèles, talons au sol', 'Genoux qui rentrent, dos rond', 'Goblet Squat', 'Box Squat', 'Douleur ou instabilité', 'Force, Débutant, Maison, Full Body', 'https://youtube.com/shorts/8voSXZyTp2A'),
('STR-002', 'Goblet Squat', 'Force', 'Bas du corps', 'Musculation', 'Intermédiaire', 'Force', 'Haltère/Kettlebell', 'Quadriceps', 'Fessiers, Core', 'Moyen', NULL, '12', '4', '90 s', 'Garder le poids proche de la poitrine', 'Pencher le buste', 'Front Squat', 'Air Squat', 'Lombalgie aiguë', 'Force, Haltère', 'https://youtube.com/shorts/Bt8lsQStck0'),
('STR-003', 'Bulgarian Split Squat', 'Force', 'Bas du corps', 'Musculation', 'Intermédiaire', 'Force unilatérale', 'Banc + Haltères', 'Quadriceps', 'Fessiers', 'Moyen', NULL, '10/jambe', '3', '90 s', 'Genou aligné avec le pied', 'Perte d''équilibre', 'Avec charge', 'Fente arrière', 'Douleur importante au genou', 'Unilatéral', 'https://youtube.com/shorts/uBSoEWZu07k'),
('STR-004', 'Walking Lunge', 'Force', 'Bas du corps', 'Musculation', 'Débutant', 'Endurance musculaire', 'Aucun', 'Quadriceps', 'Fessiers', 'Moyen', NULL, '20 pas', '3', '60 s', 'Faire de grandes foulées', 'Genou avant dépasse excessivement', 'Avec haltères', 'Fente statique', 'Douleur genou', 'Fentes', 'https://youtube.com/shorts/Agmpy7Pj1Nw'),
('STR-005', 'Glute Bridge', 'Force', 'Bas du corps', 'Musculation', 'Débutant', 'Activation fessiers', 'Aucun', 'Fessiers', 'Ischio-jambiers', 'Faible', NULL, '20', '3', '45 s', 'Monter les hanches complètement', 'Hyperextension lombaire', 'Hip Thrust', 'Bridge partiel', 'Aucune', 'Fessiers, Prévention', 'https://youtube.com/shorts/RrU4zx4ysnI'),
('STR-006', 'Hip Thrust', 'Force', 'Bas du corps', 'Musculation', 'Intermédiaire', 'Puissance hanches', 'Barre', 'Fessiers', 'Ischios', 'Moyen', NULL, '10', '4', '90 s', 'Contracter les fessiers en haut', 'Extension lombaire', 'Plus lourd', 'Glute Bridge', 'Douleur lombaire', 'Puissance', 'https://youtube.com/shorts/CvuVYMFd11g'),
('STR-007', 'Romanian Deadlift', 'Force', 'Bas du corps', 'Musculation', 'Intermédiaire', 'Chaîne postérieure', 'Barre/Haltères', 'Ischio-jambiers', 'Lombaires, Fessiers', 'Moyen', NULL, '10', '4', '90 s', 'Garder le dos neutre', 'Arrondir le dos', 'Deadlift', 'Good Morning sans charge', 'Lombalgie aiguë', 'Ischios', 'https://youtube.com/shorts/_TchJLlBO-4'),
('STR-008', 'Step Up', 'Force', 'Bas du corps', 'Musculation', 'Débutant', 'Force fonctionnelle', 'Banc', 'Quadriceps', 'Fessiers', 'Faible', NULL, '12/jambe', '3', '60 s', 'Pousser avec la jambe sur le banc', 'Prendre de l''élan avec la jambe arrière', 'Avec haltères', 'Banc plus bas', 'Douleur genou', 'Fonctionnel', 'https://youtube.com/shorts/TG3xUe-UvCQ'),
('STR-009', 'Wall Sit', 'Force', 'Bas du corps', 'Musculation', 'Débutant', 'Endurance', 'Mur', 'Quadriceps', 'Core', 'Faible', '45 s', NULL, '3', '45 s', 'Garder les cuisses parallèles', 'Monter ou descendre trop', 'Plus long', 'Angle moins fermé', 'Douleur rotulienne', 'Isométrique', 'https://youtube.com/shorts/mDdLC-yKudY'),
('STR-010', 'Box Jump', 'Force', 'Bas du corps', 'Cross Training', 'Avancé', 'Explosivité', 'Box', 'Quadriceps', 'Mollets', 'Élevé', NULL, '8', '4', '90 s', 'Atterrir en douceur', 'Genoux en valgus', 'Box plus haute', 'Squat Jump', 'Problèmes de genoux/chevilles', 'Explosivité', 'https://youtube.com/shorts/vBZ9N6KnLI8'),
('UPP-001', 'Pompes classiques', 'Force', 'Haut du corps poussée', 'Musculation', 'Débutant', 'Force / Endurance', 'Aucun', 'Pectoraux', 'Triceps, Épaules, Core', 'Faible', NULL, '12', '3', '60 s', 'Corps gainé, poitrine proche du sol', 'Hanches qui tombent, coudes trop ouverts', 'Pompes déclinées', 'Pompes sur genoux', 'Douleur aiguë à l''épaule', 'Push, Maison, Débutant', 'https://youtube.com/shorts/n8PJC6yo_1o'),
('UPP-002', 'Développé couché', 'Force', 'Haut du corps poussée', 'Musculation', 'Intermédiaire', 'Force maximale', 'Barre', 'Pectoraux', 'Triceps, Deltoïdes', 'Moyen', NULL, '8', '4', '120 s', 'Omoplates serrées, pieds ancrés', 'Rebondir sur la poitrine', 'Plus lourd', 'Développé haltères', 'Blessure épaule', 'Salle, Force', 'https://youtube.com/shorts/Jc06xowWeI4'),
('UPP-003', 'Développé haltères', 'Force', 'Haut du corps poussée', 'Musculation', 'Débutant', 'Hypertrophie', 'Haltères', 'Pectoraux', 'Triceps', 'Faible', NULL, '12', '3', '90 s', 'Mouvement contrôlé', 'Amplitude incomplète', 'Banc incliné', 'Pompes', 'Épaule instable', 'Haltères', 'https://youtube.com/shorts/xoTdvzKWib8'),
('UPP-004', 'Développé militaire', 'Force', 'Haut du corps poussée', 'Musculation', 'Intermédiaire', 'Force épaules', 'Barre', 'Deltoïdes', 'Triceps, Core', 'Moyen', NULL, '8', '4', '90 s', 'Contracter les abdos', 'Hyperlordose', 'Push Press', 'Développé haltères assis', 'Douleur cervicale', 'Épaules', 'https://youtube.com/shorts/TH8ovIkkkLk'),
('UPP-005', 'Développé Arnold', 'Force', 'Haut du corps poussée', 'Musculation', 'Intermédiaire', 'Hypertrophie épaules', 'Haltères', 'Deltoïdes', 'Triceps', 'Faible', NULL, '10', '3', '75 s', 'Rotation fluide', 'Rotation trop rapide', 'Plus lourd', 'Développé haltères', 'Douleur épaule', 'Arnold Press', 'https://youtube.com/shorts/KYYNNj4v2J0'),
('UPP-006', 'Dips', 'Force', 'Haut du corps poussée', 'Musculation', 'Avancé', 'Force', 'Barres parallèles', 'Triceps', 'Pectoraux', 'Élevé', NULL, '10', '4', '90 s', 'Descendre sous les 90° sans douleur', 'Épaules qui remontent', 'Dips lestés', 'Bench Dips', 'Épaule instable', 'Triceps', 'https://youtube.com/shorts/CrbIq-T-h8I'),
('UPP-007', 'Push Press', 'Force', 'Haut du corps poussée', 'Haltérophilie', 'Avancé', 'Puissance', 'Barre', 'Deltoïdes', 'Triceps, Jambes', 'Moyen', NULL, '6', '5', '120 s', 'Utiliser l''impulsion des jambes', 'Pousser uniquement avec les bras', 'Plus lourd', 'Développé militaire', 'Lombalgie aiguë', 'Puissance', 'https://youtube.com/shorts/VaIDqmZBkpc'),
('UPP-008', 'Landmine Press', 'Force', 'Haut du corps poussée', 'Musculation', 'Intermédiaire', 'Force fonctionnelle', 'Barre Landmine', 'Deltoïdes', 'Pectoraux, Core', 'Faible', NULL, '10/bras', '3', '75 s', 'Pousser dans l''axe', 'Rotation du tronc', 'Debout unilatéral', 'Développé haltères', 'Aucune spécifique', 'Fonctionnel', 'https://youtube.com/shorts/Iu5pYQEkj38'),
('UPP-009', 'Pompes explosives', 'Force', 'Haut du corps poussée', 'Préparation physique', 'Avancé', 'Explosivité', 'Aucun', 'Pectoraux', 'Triceps', 'Moyen', NULL, '8', '5', '90 s', 'Décoller les mains rapidement', 'Mauvaise réception', 'Pompes claquées', 'Pompes classiques', 'Poignets douloureux', 'Explosivité', 'https://youtube.com/shorts/2JxSJyt_IMk'),
('UPP-010', 'Pike Push-Up', 'Force', 'Haut du corps poussée', 'Calisthenics', 'Intermédiaire', 'Force verticale', 'Aucun', 'Deltoïdes', 'Triceps', 'Moyen', NULL, '10', '3', '60 s', 'Descendre la tête entre les mains', 'Dos arrondi', 'Handstand Push-Up', 'Pompes inclinées', 'Douleur cervicale', 'Poids du corps', 'https://youtube.com/shorts/UalsVVpBacw'),
('THC-001', 'Tractions pronination (Pull-ups)', 'Force', 'Haut du corps tirage', 'Calisthenics', 'Avancé', 'Force dos / Largeur', 'Barre de traction', 'Grand dorsal', 'Biceps, Grand rond, Trapèzes', 'Moyen', NULL, '6', '3', '90 s', 'Prise un peu plus large que les épaules, tirer les coudes vers le bas', 'Balancement du corps, amplitude incomplète', 'Tractions lestées', 'Tractions assistées avec élastique', 'Douleur aiguë à l''épaule ou au coude', 'Dos, Largeur, Avancé', 'https://youtube.com/shorts/ym1V5H35IpA'),
('THC-002', 'Tractions supination (Chin-ups)', 'Force', 'Haut du corps tirage', 'Calisthenics', 'Intermédiaire', 'Force dos et biceps', 'Barre de traction', 'Grand dorsal', 'Biceps brachial', 'Moyen', NULL, '8', '3', '90 s', 'Paumes de mains vers soi, prise largeur d''épaules', 'Ne pas tendre complètement les bras en bas', 'Tractions supination lestées', 'Tractions australiennes', 'Tendinite au coude', 'Biceps, Dos, Intermédiaire', 'https://youtube.com/shorts/Oi3bW9nQmGI'),
('THC-003', 'Tirage horizontal unilatéral aux haltères (Rowing)', 'Force', 'Haut du corps tirage', 'Musculation', 'Débutant', 'Épaisseur du dos', 'Banc et Haltère', 'Grand dorsal', 'Romboïdes, Biceps, Trapèzes', 'Faible', NULL, '10/bras', '3', '75 s', 'Un genou et une main sur le banc, tirer l''haltère vers la hanche', 'Rotation excessive du tronc, tirer avec le bras', 'Rowing barre lourd', 'Rowing buste penché léger', 'Lombalgie sensible', 'Dos, Unilatéral, Maison', 'https://youtube.com/shorts/vu_YDt9nGv4'),
('THC-004', 'Rowing buste penché aux haltères', 'Force', 'Haut du corps tirage', 'Musculation', 'Intermédiaire', 'Épaisseur globale du dos', 'Haltères', 'Grand dorsal', 'Romboïdes, Érecteurs du rachis', 'Moyen', NULL, '10', '3', '90 s', 'Buste penché à 45°, dos plat', 'Arrondir le dos pendant le tirage', 'Rowing barre olympique', 'Rowing sur banc incliné', 'Hernie discale', 'Dos, Épaisseur', 'https://youtube.com/shorts/dpYI8K6e-jE'),
('THC-005', 'Tractions australiennes (Inverted Row)', 'Force', 'Haut du corps tirage', 'Calisthenics', 'Débutant', 'Renforcement dos accessible', 'Barre fixe basse ou TRX', 'Grand dorsal', 'Romboïdes, Biceps', 'Faible', NULL, '12', '3', '60 s', 'Corps aligné sous la barre, tirer la poitrine contre la barre', 'Laisser creuser les hanches', 'Tractions classiques', 'Tractions australiennes jambes fléchies', 'Aucune spécifique', 'Débutant, Maison, TRX', 'https://youtube.com/shorts/qfsEK96Px-E'),
('COR-001', 'Gainage planche forearm (Plank)', 'Gainage', 'Core', 'Calisthenics', 'Débutant', 'Stabilité lombo-abdominale', 'Aucun', 'Grand droit de l''abdomen', 'Transverse, Épaules, Fessiers', 'Faible', '45 s', NULL, '3', '45 s', 'Appui sur les avant-bras et pointes de pieds, bassin en rétroversion', 'Fesses trop hautes ou bassin qui s''affaisse', 'Planche dynamique / sur une main', 'Planche sur les genoux', 'Lombalgie aiguë en extension', 'Core, Maison, Débutant', 'https://youtube.com/shorts/E-PBfoIMc-0'),
('COR-002', 'Gainage latéral (Side Plank)', 'Gainage', 'Core', 'Calisthenics', 'Intermédiaire', 'Stabilité latérale / Obliques', 'Aucun', 'Obliques', 'Carré des lombaires, Moyen fessier', 'Faible', '30 s/côté', NULL, '3', '45 s', 'Appui sur l''avant-bras latéral, alignement parfait', 'Hanches qui piquent vers le sol', 'Gainage latéral avec élévation de jambe', 'Gainage latéral sur les genoux', 'Douleur à l''épaule d''appui', 'Core, Obliques, Unilatéral', 'https://youtube.com/shorts/eZQRj1yG-gY'),
('COR-003', 'Bird Dog (Quadrupède)', 'Gainage', 'Core', 'Calisthenics', 'Débutant', 'Stabilité rachidienne / Posture', 'Aucun', 'Érecteurs du rachis', 'Fessiers, Core', 'Faible', NULL, '10/côté', '3', '60 s', 'À quatre pattes, tendre bras droit et jambe gauche sans bouger le bassin', 'Rotation du bassin lors de l''extension', 'Bird Dog avec résistance élastique', 'Extension unilatérale bras seul', 'Aucune spécifique', 'Core, Santé du dos, Débutant', 'https://youtube.com/shorts/vtwhC3tfVow'),
('COR-004', 'Dead Bug', 'Gainage', 'Core', 'Calisthenics', 'Débutant', 'Contrôle lombo-pelvien', 'Aucun', 'Transverse de l''abdomen', 'Fléchisseurs de la hanche', 'Faible', NULL, '10/côté', '3', '60 s', 'Allongé sur le dos, bras levés, genoux à 90°', 'Lombales qui se décollent du sol', 'Dead Bug avec charge aux mains', 'Dead Bug jambes fléchies', 'Douleur lombaire', 'Core, Posture, Abdominaux', 'https://youtube.com/shorts/5c-vucY3beU'),
('COR-005', 'Mountain Climbers', 'Gainage', 'Core / Cardio', 'Préparation physique', 'Intermédiaire', 'Cardio & Gainage dynamique', 'Aucun', 'Core', 'Épaules, Quadriceps', 'Moyen', '45 s', NULL, '3', '60 s', 'Position de pompe, ramener alternativement les genoux vers la poitrine', 'Fesses qui montent trop haut', 'Mountain climbers rapides ou croisés', 'Mountain climbers lents en marchant', 'Douleur aux poignets', 'Core, Cardio, Dynamique', 'https://youtube.com/shorts/7W4JEfEKuC4'),
('CAR-001', 'Jumping Jacks', 'Cardio', 'Cardio basique', 'Préparation physique', 'Débutant', 'Endurance cardiovasculaire', 'Aucun', 'Système cardiovasculaire', 'Mollets, Épaules', 'Faible', '45 s', NULL, '3', '45 s', 'Sauter en écartant les jambes et en levant les bras', 'Amorti trop lourd sur les articulations', 'Jumping Jacks rythmés lestés', 'Jumping Jacks sans saut', 'Douleur aux genoux ou chevilles', 'Cardio, Échauffement, Maison', 'https://youtube.com/shorts/yg3KQQn3QWg'),
('CAR-002', 'Corde à sauter', 'Cardio', 'Cardio dynamique', 'Préparation physique', 'Intermédiaire', 'Agilité / Cardio', 'Corde à sauter', 'Système cardiovasculaire', 'Mollets, Avant-bras', 'Moyen', '60 s', NULL, '3', '60 s', 'Sauts courts impulsés par les poignets', 'Sauter trop haut ou utiliser les bras', 'Double unders', 'Sauts sur place sans corde', 'Fasciite plantaire / Douleur tibiale', 'Cardio, Agilité', 'https://youtube.com/shorts/iWa7KVOyAlU'),
('CAR-003', 'Burpees sans pompe', 'Cardio', 'Cardio / Full Body', 'Préparation physique', 'Intermédiaire', 'Puissance aérobie', 'Aucun', 'Corps entier', 'Quadriceps, Pectoraux, Core', 'Élevé', NULL, '10', '3', '75 s', 'Passer accroupi, envoyer les pieds en arrière, ramener et sauter', 'Laisser creuser le dos en planche', 'Burpees complets avec pompe et saut', 'Burpees en marchant', 'Lombalgie ou douleur poignets', 'Cardio, Intensité', 'https://youtube.com/shorts/GJ2oJUrsm7s'),
('CAR-004', 'High Knees (Genoux montants)', 'Cardio', 'Cardio dynamique', 'Préparation physique', 'Débutant', 'Explosivité / Cardio', 'Aucun', 'Système cardiovasculaire', 'Fléchisseurs de la hanche, Mollets', 'Moyen', '45 s', NULL, '3', '45 s', 'Courir sur place en montant les genoux, dos droit', 'Se pencher en arrière pendant la course', 'High knees rapides avec résistance', 'Montées de genoux marchées', 'Douleur de hanche', 'Cardio, Vitesse', 'https://youtube.com/shorts/0X0Q8wKLEfo'),
('CAR-005', 'Skater Jumps', 'Cardio', 'Cardio latéral', 'Préparation physique', 'Intermédiaire', 'Agilité latérale / Fessiers', 'Aucun', 'Moyen fessier', 'Quadriceps, Système cardiovasculaire', 'Moyen', '45 s', NULL, '3', '45 s', 'Sauter latéralement d''une jambe sur l''autre', 'Perte d''équilibre à la réception', 'Skater jumps amples et rapides', 'Pas chassés latéraux', 'Instabilité de cheville', 'Cardio, Latéral, Agilité', 'https://youtube.com/shorts/qM5jviFhw9U'),
('MOB-001', 'World''s Greatest Stretch', 'Mobilité', 'Mobilité globale', 'Mobilité', 'Débutant', 'Mobilité hanches et thoracique', 'Aucun', 'Hanches', 'Colonne thoracique, Ischio-jambiers', 'Faible', NULL, '5/côté', '2', '45 s', 'Grande fente avant, poser le coude au sol, puis rotation vers le ciel', 'Précipitation du mouvement', 'World''s Greatest stretch avec rotation ample', 'Version simplifiée genou posé', 'Aucune spécifique', 'Mobilité, Échauffement', 'https://youtube.com/shorts/kSPS_HIQv8E'),
('MOB-002', 'Cat-Cow (Chat-Vache)', 'Mobilité', 'Colonne vertébrale', 'Mobilité', 'Débutant', 'Mobilité vertébrale', 'Aucun', 'Colonne vertébrale', 'Core', 'Faible', '60 s', NULL, '2', '30 s', 'À quatre pattes, alterner dos rond et dos creusé', 'Mouvement brusque au niveau cervical', 'Cat-Cow avec pauses amples', 'Amplitude réduite', 'Douleur dorsale aiguë', 'Mobilité, Dos, Douceur', 'https://youtube.com/shorts/2of247Kt0tU'),
('MOB-003', 'Mobilité des chevilles contre un mur', 'Mobilité', 'Bas du corps', 'Mobilité', 'Débutant', 'Dorsiflexion de cheville', 'Mur', 'Chevilles', 'Mollets', 'Faible', NULL, '10/jambe', '2', '30 s', 'Pied à 10 cm du mur, avancer le genou pour toucher le mur', 'Décoller le talon du sol', 'Mobilisation cheville avec élastique', 'Pied plus près du mur', 'Entorse récente', 'Mobilité, Chevilles', 'https://youtube.com/shorts/sP8HXhZ7iE8'),
('MOB-004', 'Ouverture thoracique (T-Spine rotation)', 'Mobilité', 'Haut du corps', 'Mobilité', 'Débutant', 'Mobilité thoracique', 'Tapis', 'Colonne thoracique', 'Épaules', 'Faible', NULL, '10/côté', '2', '30 s', 'Allongé sur le côté genoux fléchis à 90°, ouvrir le bras en grand', 'Décoller les genoux du sol pendant la rotation', 'Rotation thoracique assise', 'Amplitude partielle', 'Douleur d''épaule', 'Mobilité, Dos haut', 'https://youtube.com/shorts/cncdlzYmbxg'),
('MOB-005', 'Mobilité des hanches 90/90', 'Mobilité', 'Bas du corps', 'Mobilité', 'Intermédiaire', 'Rotation interne/externe des hanches', 'Aucun', 'Hanches', 'Fessiers', 'Faible', '60 s', NULL, '2', '30 s', 'Assis au sol, jambes fléchies à 90°, basculer les genoux de gauche à droite', 'S''aider des mains de manière excessive', '90/90 sans les mains', 'Amplitude réduite avec appui arrière', 'Douleur de hanche', 'Mobilité, Hanches', 'https://youtube.com/shorts/fDC2KC1XqY8'),
('FB-001', 'Thruster haltères', 'Full Body', 'Poussée & Bas du corps', 'Musculation', 'Intermédiaire', 'Puissance globale / Métabolique', 'Haltères', 'Corps entier', 'Quadriceps, Deltoïdes, Core', 'Élevé', NULL, '10', '3', '90 s', 'Squat complet suivi d''une poussée explosive des bras', 'Pousser avec les bras avant d''avoir fini l''extension', 'Thruster lourd', 'Thruster au poids du corps', 'Lombalgie ou épaule douloureuse', 'Full Body, Métabolique', 'https://youtube.com/shorts/M2LaTuuOyv4'),
('FB-002', 'Kettlebell Swing', 'Full Body', 'Chaîne postérieure', 'Haltérophilie', 'Débutant', 'Explosivité / Chaîne postérieure', 'Kettlebell', 'Fessiers', 'Ischio-jambiers, Lombaire, Épaules', 'Moyen', NULL, '15', '3', '60 s', 'Charnière de hanche, propulser le kettlebell par l''impulsion des fessiers', 'Squatter le mouvement au lieu de charnière', 'Kettlebell swing lourd ou américain', 'Kettlebell deadlift simple', 'Lombalgie aiguë', 'Full Body, Puissance', 'https://youtube.com/shorts/3lMRRqyTuK8'),
('FB-003', 'Burpees avec pompe complète', 'Full Body', 'Cardio / Renforcement', 'Préparation physique', 'Avancé', 'Conditionnement total', 'Aucun', 'Corps entier', 'Pectoraux, Quadriceps, Core', 'Élevé', NULL, '10', '3', '90 s', 'Descendre en squat, poser les mains, faire une pompe, ramener et sauter', 'Affaissement des lombaires en remontant', 'Burpees avec saut sur box', 'Burpees sans pompe', 'Douleur poignets ou épaules', 'Full Body, Intense', 'https://youtube.com/shorts/QDttLyGKhQk'),
('FB-004', 'Manmaker (Haltères)', 'Full Body', 'Mixte force & cardio', 'Musculation', 'Avancé', 'Force fonctionnelle totale', 'Haltères', 'Corps entier', 'Dos, Pectoraux, Épaules, Jambes', 'Élevé', NULL, '6', '3', '120 s', 'Pompe sur haltères, rowing par bras, saut groupé, épaulé-jeté', 'Vouloir aller trop vite au détriment de la posture', 'Manmaker lourd', 'Manmaker sans la charge', 'Lombalgie ou fatigue excessive', 'Full Body, Avancé', 'https://youtube.com/shorts/DjTryuo3T6s'),
('FB-005', 'Clean and Press avec kettlebell', 'Full Body', 'Combinés / Poussée verticale', 'Haltérophilie', 'Intermédiaire', 'Puissance globale', 'Kettlebell', 'Corps entier', 'Épaules, Fessiers, Quadriceps', 'Moyen', NULL, '8/bras', '3', '90 s', 'Amener le kettlebell à l''épaule par un tirage explosif des hanches, puis développer', 'Tirer avec le bras au lieu de projeter avec les hanches', 'Clean and Press lourd avec barre', 'Épaulé simple sans développé', 'Douleur poignet ou épaule', 'Full Body, Puissance', 'https://youtube.com/shorts/h4KafmF7Xwc'),
('BOX-001', 'Shadow Boxe 5 (jab, cross, hook, uppercut)', 'Boxe', 'Frappes de base', 'Boxe', 'Débutant', 'Cardio / Coordination', 'Aucun', 'Épaules', 'Core, Système cardiovasculaire', 'Faible', '60 s', NULL, '3', '45 s', 'Garde haute, lancer le Jab puis le Cross en pivotant le pied', 'Tendre complètement le coude de manière brusque', 'Shadow boxe avec petits haltères', 'Shadow boxe lent face à un miroir', 'Douleur au coude', 'Boxe, Cardio, Technique', 'https://youtube.com/shorts/LMhVqtK3p_Y'),
('BOX-002', 'Crochets et Uppercuts en shadow', 'Boxe', 'Frappes circulaires', 'Boxe', 'Intermédiaire', 'Puissance rotationnelle / Cardio', 'Aucun', 'Core / Obliques', 'Épaules, Hanches', 'Moyen', '60 s', NULL, '3', '45 s', 'Pivoter sur les appuis pour lancer crochets et uppercuts', 'Oublier la rotation du bassin et des pieds', 'Shadow avec résistance élastique', 'Shadow direct uniquement', 'Douleur lombaire par torsion sèche', 'Boxe, Obliques, Dynamique', 'https://youtube.com/shorts/a1PAFI8OYis'),
('BOX-003', 'Esquives rotatives (Slip & Roll)', 'Boxe', 'Défense', 'Boxe', 'Intermédiaire', 'Agilité / Coordination défensive', 'Aucun', 'Core', 'Jambes, Hanches', 'Faible', '60 s', NULL, '3', '45 s', 'Fléchir les jambes et pivoter le buste en ''U'' pour esquiver', 'Pencher le buste en avant sans plier les genoux', 'Esquives suivies d''une contre-attaque', 'Esquives lentes sur place', 'Douleur cervicale', 'Boxe, Défense, Mobilité', 'https://youtube.com/shorts/EWykTUVMMpY'),
('BOX-004', 'Shadow Boxe avec déplacements (Footwork)', 'Boxe', 'Déplacements', 'Boxe', 'Avancé', 'Jambes / Agilité en combat', 'Aucun', 'Jambes', 'Système cardiovasculaire, Core', 'Moyen', '90 s', NULL, '3', '60 s', 'Se déplacer en pas chassés, avancer et reculer en gardant toujours sa garde', 'Croiser les pieds pendant les déplacements latéraux', 'Shadow avec frappes en mouvement', 'Déplacements simples sur une ligne', 'Instabilité de cheville', 'Boxe, Agilité, Avancé', 'https://youtube.com/shorts/L30WFJ7d1BA')
ON CONFLICT (code_id) DO UPDATE SET
    name = EXCLUDED.name,
    family = EXCLUDED.family,
    subfamily = EXCLUDED.subfamily,
    discipline = EXCLUDED.discipline,
    level = EXCLUDED.level,
    objective = EXCLUDED.objective,
    material = EXCLUDED.material,
    main_zone = EXCLUDED.main_zone,
    secondary_zones = EXCLUDED.secondary_zones,
    joint_impact = EXCLUDED.joint_impact,
    duration = EXCLUDED.duration,
    repetitions = EXCLUDED.repetitions,
    series = EXCLUDED.series,
    rest = EXCLUDED.rest,
    instructions = EXCLUDED.instructions,
    common_mistakes = EXCLUDED.common_mistakes,
    progression = EXCLUDED.progression,
    regression = EXCLUDED.regression,
    contraindications = EXCLUDED.contraindications,
    tags = EXCLUDED.tags,
    video_url = EXCLUDED.video_url;
